### ISSUE TITLE
Gemfile became outdated

### ISSUE THREAD

**Issue by mkordas** [yegor256/rultor#1037]
All dependency versions should be locked in and explicitly specified.

The issue currently blocking merges. 

Log:
```
Using kramdown 1.10.0
Using liquid 2.6.3
Using mercenary 0.3.5
Using posix-spawn 0.3.11
Using yajl-ruby 1.2.1
Using redcarpet 3.3.4
Using safe_yaml 1.0.4
Using trollop 2.0
Using mime-types 2.99.1
Using mini_portile2 2.0.0
Using uuidtools 2.1.5
Using bundler 1.11.2
Using parslet 1.5.0
Using classifier-reborn 2.0.4
Using coffee-script 2.4.1
Using css_press 0.3.2
Using uglifier 2.7.2
Using faraday 0.9.2
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.4.0
Using pygments.rb 0.6.3
Using mail 2.6.3
Using nokogiri 1.6.7.2
Using toml 0.1.2
Using jekyll-coffeescript 1.0.1
Using multi_css 0.1.0
Using multi_js 0.1.0
Using sawyer 0.6.0
Using listen 3.0.6
Using html_press 0.8.2
Using octokit 4.2.0
Using jekyll-watch 1.3.1
Using jekyll-gist 1.4.0
Using jekyll 2.4.0
Using jekyll-plantuml 1.0.2
Using jekyll-press 0.2.1
Using jekyll-sass 1.2.2
Using jgd 1.3
\u001b[32mBundle updated!\u001b[0m
+ bundle show jekyll
/var/lib/gems/2.2.0/gems/jekyll-2.4.0
+ jekyll --version
/var/lib/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
    from /var/lib/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in `<module:SafeYAML>'
    from /var/lib/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /var/lib/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in `<module:SafeYAML>'
    from /var/lib/gems/2.2.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /var/lib/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll.rb:28:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /var/lib/gems/2.2.0/gems/jekyll-3.1.2/bin/jekyll:6:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'
container de5ccf5908ebba1e53fe8898cc969120a8776bb533226004c8fbc3e2a28dc226 is dead
Wed Mar  2 23:09:40 UTC 2016
```

**Comment by original-brownbear** [comment]
@alex-palevsky this is a bug.

**Comment by original-brownbear** [comment]
@alex-palevsky this is urgent.

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a bug.

@original-brownbear tag bug added to this issue

**Comment by alex-palevsky** [comment]
@mkordas attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is urgent.

@original-brownbear thanks, I added "urgent" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign me please.

@original-brownbear yep, it is yours, go ahead

**Comment by alex-palevsky** [comment]
@mkordas thank you for reporting this, I added 15 mins to your acc, transaction `56d88b05ae4b9833310003c7`

**Comment by original-brownbear** [comment]
@mkordas can you close this?, evidently fixed now :)

**Comment by original-brownbear** [comment]
@alex-palevsky can you close this in my agenda please ? :)

**Comment by alex-palevsky** [comment]
@original-brownbear **1 hour** added to your account (payment number `AP-9CV61555ET713041W`), many thanks for your contribution! 17 hours and 27 mins spent here.

m=1047, that's why a bonus here for fast delivery

+60 added to your rating, at the moment it is: [+872](http://www.netbout.com/b/36646?open=rating)
