### ISSUE TITLE
TailITCase.tailsNonUtf fails on Mac OS X

### ISSUE THREAD

**Issue by essobedo** [yegor256/rultor#1061]
When trying to build Rultor with Java 7 I get the following error:
```
tailsNonUtf(com.rultor.agents.daemons.TailITCase)  Time elapsed: 1.943 sec  <<< ERROR!
java.io.IOException: com.jcraft.jsch.JSchException: Algorithm negotiation fail
	at com.jcabi.ssh.SSH.session(SSH.java:279)
	at com.jcabi.ssh.SSH.exec(SSH.java:219)
	at com.rultor.agents.daemons.Tail$SSHConnect.read(Tail.java:237)
	at com.rultor.agents.daemons.Tail.read(Tail.java:142)
	at com.rultor.agents.daemons.TailITCase.tailsNonUtf(TailITCase.java:95)

Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
	at com.jcraft.jsch.Session.receive_kexinit(Session.java:583)
	at com.jcraft.jsch.Session.connect(Session.java:320)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:275)
	... 24 more
```
If I try to build Rultor with Java 8 I get the following error:
```
java.lang.AssertionError: 
Expected: is "some outputê\n"
     but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.rultor.agents.daemons.TailITCase.tailsNonUtf(TailITCase.java:95)
```
We should be able to build Rultor on Mac OS X according to this [note](https://github.com/yegor256/rultor/blob/master/pom.xml#L873-L875).

If this particular test cannot be fixed on Mac OS X, it could be nice to have a specific maven profile that will be enabled if mac is detected in order to exclude this test which will allow mac users to build Rultor without having to rely on any virtualization mechanism such as Docker.

**Comment by original-brownbear** [comment]
@essobedo working on a better solution than that here #1055 :) it's incoming.

**Comment by essobedo** [comment]
@original-brownbear ok thx so I close it then
