### ISSUE TITLE
EC2 Instance is down

### ISSUE THREAD

**Issue by original-brownbear** [yegor256/rultor#1063]
@yegor256 please take a look as soon as you can.

I'm seeing this right now. Indicating the EC2 instance itself is down.

```
java.io.IOException: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcabi.ssh.SSH.session(SSH.java:279)
	at com.jcabi.ssh.SSH.exec(SSH.java:219)
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:103)
	at com.rultor.agents.docker.DockerExec.execute(DockerExec.java:72)
	at com.rultor.spi.SuperAgent$Iterative.execute(SuperAgent.java:76)
	at com.rultor.Routine.process(Routine.java:159)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:275)
	... 21 more
```

Also I think we need to come up with some contingency plan for this situation. While the situation of the Docker daemon halting is close to resolved for good, the EC2 instance itself needs a different approach.

Given that Rultor is supposed to be able to provision EC2 instances anyhow, I'd ask for restarting the instance being implemented here unless this is not something you want at this point?

**Comment by original-brownbear** [comment]
@yegor256 The Docker service is still down I think, can you check that too ?

**Comment by original-brownbear** [comment]
Closing this is up and running again, we have tickets for the general issue with EC2 already.

**Comment by original-brownbear** [comment]
@yegor256 please restart this again asap.

**Comment by original-brownbear** [comment]
@yegor256 down again, please restart.

**Comment by original-brownbear** [comment]
@yegor256 appears its back ....

**Comment by yegor256** [comment]
@original-brownbear we desperately need to move to on-demand EC2 instances. we're getting more projects on board and one Docker server is simply not stable enough (despite all that millions of dollars invested). so, let's focus on moving to on-demand machines!

**Comment by original-brownbear** [comment]
@yegor256

It's down again ..., did anything change with that machine?
Should I look into that machine maybe? This dying so frequently seems to be some new issue with that machine.

As for on-demand:
I'm on that personally now in #1066, urgency is understood.

**Comment by original-brownbear** [comment]
@yegor256 we finally have a useful error message, there is no space on the EC2 left!

**Comment by original-brownbear** [comment]
@yegor256  we finally have a useful error message in one of our projects , there is no space on the EC2 left! 

Maybe just run a 
```
docker rm -f -v $(docker ps -aq) 
```

Followed by 

```
docker rmi -f $(docker images -q) 
```
and start fresh ...?

**Comment by original-brownbear** [comment]
@yegor256 ping.

**Comment by sils1297** [comment]
Any news?

**Comment by yegor256** [comment]
@original-brownbear there is enough space:

```
$ df
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/xvda1     377476072 311157772  66318300  83% /
devtmpfs         7597596         0   7597596   0% /dev
tmpfs            7486540         0   7486540   0% /dev/shm
tmpfs            7486540    197372   7289168   3% /run
tmpfs            7486540         0   7486540   0% /sys/fs/cgroup
tmpfs            1497312         0   1497312   0% /run/user/1003
tmpfs            1497312         0   1497312   0% /run/user/1002
tmpfs            1497312         0   1497312   0% /run/user/1001
```

**Comment by original-brownbear** [comment]
@yegor256 the space on the HD doesn't matter. What matters is the free space of the Docker overlay fs.

What's the output of `docker info` ?

**Comment by yegor256** [comment]
@original-brownbear here you go:

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 48
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-276824258-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 107.4 GB
 Data Space Total: 107.4 GB
 Data Space Available: 0 B
 Metadata Space Used: 239.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.908 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82 (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.28 GiB
Name: cron4.wobot.net
ID: NV4D:YU5R:DI4Y:2E5D:VIG5:RZAV:2UX7:PVED:BCOZ:UMQB:OSJX:IP56
Username: yegor256
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by original-brownbear** [comment]
@yegor256 it's full

```
Data Space Used: 107.4 GB
 Data Space Total: 107.4 GB
 Data Space Available: 0 B
```

**Comment by yegor256** [comment]
@original-brownbear what should I do?

**Comment by original-brownbear** [comment]
@yegor256 as I said above, unless you feel like you need to keep anything in the docker daemon around ( not needed from the Rultor perspective ) run this:

Kill all containers first : `docker rm -f -v $(docker ps -aq) `
Then delete all images: `docker rmi -f $(docker images -q) ` (could take a few minutes)

**Comment by yegor256** [comment]
@original-brownbear `rmi` is still running...

**Comment by original-brownbear** [comment]
@yegor256 it can take quite a while. I suggest, given the time pressure we're already under to maybe Cntrl+C it for now ( its not an issue, it can be interrupted safely, a better solution is incoming anyhow ).
You can check that we have free space in a different shell running `docker info`, but I think for now we should be good after almost one hour of `rmi`.

**Comment by yegor256** [comment]
@original-brownbear I stopped it (Ctrl-C), but nothing changed. all images are still there and 0Mb is available... I will try to delete images one by one

**Comment by original-brownbear** [comment]
@yegor256 that does not sound good ... almost sounds like the overlay fs is corrupted somehow. If deleting images one by one does not work or throws any warnings/errors, I strongly suggest removing Docker from that server, deleting `/var/lib/docker` and reinstalling it.

**Comment by yegor256** [comment]
@original-brownbear doing it now... rebooting first. I couldn't stop docker daemon in a legal way.

**Comment by yegor256** [comment]
@original-brownbear done:

```
$ sudo rm -rf /var/lib/docker/
$ sudo service docker start
Redirecting to /bin/systemctl start  docker.service
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-1501563778-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 68.46 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82 (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.28 GiB
Name: cron4.wobot.net
ID: NV4D:YU5R:DI4Y:2E5D:VIG5:RZAV:2UX7:PVED:BCOZ:UMQB:OSJX:IP56
Username: yegor256
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by original-brownbear** [comment]
@yegor256 thanks!

**Comment by sils1297** [comment]
I can confirm that it works again FWIW

**Comment by original-brownbear** [comment]
@sils1297 perfect, thanks! :)
