### ISSUE TITLE
Rultor down again

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#1097]
A quick fix even with a workaround would be well appreciated.

**Comment by original-brownbear** [comment]
@yegor256 ping , this looks like a problem on Heroku for a change.

**Comment by yegor256** [comment]
@original-brownbear this is what is happening: 

```
There is no activity yet, refresh in a few seconds

java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:149)
	at java.lang.StringCoding.decode(StringCoding.java:193)
	at java.lang.String.<init>(String.java:416)
	at java.io.ByteArrayOutputStream.toString(ByteArrayOutputStream.java:245)
	at com.jcabi.ssh.Shell$Plain.exec(Shell.java:176)
	at com.rultor.agents.daemons.ShellCommand.exec(ShellCommand.java:86)
	at com.rultor.agents.daemons.EndsDaemon.end(EndsDaemon.java:106)
	at com.rultor.agents.daemons.EndsDaemon.process(EndsDaemon.java:91)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@original-brownbear I will try to fix it now myself

**Comment by original-brownbear** [comment]
@yegor256 did you try restarting it on Heroku ?

This looks like some huge output from a run killed it on the surface, but I don't see how this would be recurring on repeated runs. => Something must be up on Heroku. Can you see the memory situation there?

**Comment by yegor256** [comment]
@original-brownbear yeah, the problem is that someone produced too big output. I'm fixing it now...

**Comment by yegor256** [comment]
@original-brownbear will try to deploy this now: 00486fd

**Comment by yegor256** [comment]
@original-brownbear it seems to be fixed

**Comment by yegor256** [comment]
@rultor release, tag is `1.61.9`

**Comment by yegor256** [comment]
@sils1297 please, check it now. should be working without issues

**Comment by sils1297** [comment]
Yes it does, thanks!

**Comment by yegor256** [comment]
@sils1297 please close the ticket :)
