### ISSUE TITLE
Connection is closed by foreign host

### ISSUE THREAD

**Issue by jachinte** [yegor256/rultor#1098]
Hello,

I asked rultor to release a new version in [this](https://github.com/unicesi/pascani/issues/11) issue. After a while it failed with the stacktrace:

```
java.io.IOException: com.jcraft.jsch.JSchException: connection is closed by foreign host
	at com.jcabi.ssh.SSH.session(SSH.java:279)
	at com.jcabi.ssh.SSH.exec(SSH.java:219)
	at com.rultor.agents.daemons.Tail$SSHConnect.read(Tail.java:237)
	at com.rultor.agents.daemons.Tail.read(Tail.java:142)
	at com.rultor.web.TkDaemon.html(TkDaemon.java:129)
	at com.rultor.web.TkDaemon.act(TkDaemon.java:106)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:91)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:81)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:51)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:63)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:98)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jcraft.jsch.JSchException: connection is closed by foreign host
	at com.jcraft.jsch.Session.connect(Session.java:269)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:275)
	... 38 more
```

The rultor link is [8310-218468633](http://www.rultor.com/t/8310-218468633)

**Comment by jachinte** [comment]
> Unfortunately, the system is down, for 2hr already

**Comment by original-brownbear** [comment]
@yegor256 help please.

**Comment by jachinte** [comment]
It's working now.
