### ISSUE TITLE
Invalid rultor.yml has caused a system outage

### ISSUE THREAD

**Issue by orthodoc** [yegor256/rultor#1100]
Related to Issue #1032

**Comment by yegor256** [comment]
@original-brownbear this is how it looks:

```
com.rultor.spi.Profile$ConfigException: while parsing a block mapping
 in 'string', line 13, column 3:
      credentials: "orthodoc/DxProd#AW ... 
      ^
expected <block end>, but found Scalar
 in 'string', line 15, column 42:
     ... ionVariables: "orthodoc/DxProd#"dx-backend/_meta/variables/s-var ... 
                                         ^

	at com.rultor.profiles.YamlXML.get(YamlXML.java:82)
	at com.rultor.profiles.GithubProfile.read(GithubProfile.java:122)
	at com.rultor.profiles.ProfileDeprecations.print(ProfileDeprecations.java:86)
	at com.rultor.agents.daemons.EndsDaemon.process(EndsDaemon.java:95)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
Caused by: while parsing a block mapping
 in 'string', line 13, column 3:
      credentials: "orthodoc/DxProd#AW ... 
      ^
expected <block end>, but found Scalar
 in 'string', line 15, column 42:
     ... ionVariables: "orthodoc/DxProd#"dx-backend/_meta/variables/s-var ... 
                                         ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
	at com.rultor.profiles.YamlXML.get(YamlXML.java:80)
	... 22 more
```

**Comment by yegor256** [comment]
@orthodoc can you please fix your `.rultor.yml` for now, to put the system back online? we'll fix the bug tomorrow

**Comment by orthodoc** [comment]
@yegor256 I did that. Will wait for system to be back.

**Comment by original-brownbear** [comment]
@alex-palevsky this is a but.

**Comment by original-brownbear** [comment]
@alex-palevsky this is a bug.

**Comment by original-brownbear** [comment]
@yegor256 Ok if I'll deal with this first thing tomorrow morning?

**Comment by original-brownbear** [comment]
@alex-palevsky assign me please, this is kinda urgent :)

**Comment by yegor256** [comment]
@original-brownbear yes, please. I actually don't know how we can solve that... what should `EndDaemon` do if there are problems in `.rultor.yml`? inform the user? how many times? for now, we can just skip the execution and swallow the exception. but this is not a solution, since the user will never know what is happening and will sit and wait and wait...

**Comment by yegor256** [comment]
@original-brownbear I think it's rather urgent... can you fix it right away or you need my help?

**Comment by original-brownbear** [comment]
@yegor256 would get on with it in the next 5-10 min :)

**Comment by yegor256** [comment]
@original-brownbear thanks! we're down for over 7 hours :( that's not cool

**Comment by original-brownbear** [comment]
@yegor256 On it now, how about just informing the user on every actual request and ignoring on "hello".
So if you go "merge please", you'll get told your `.rultor.yml` is broken, if you say "hello" you get no warning since the `.rultor.yml` is not relevant for that?
I mean it makes no sense simply stopping to inform about the busted config file at any point does it? What then, start completely ignoring the repo/user?

=> Keep informing the user as often has he pings Rultor with a valid command imo.
Makes sense ?

**Comment by yegor256** [comment]
@original-brownbear what you're suggesting works already. we won't start a job if configuration is broken. but the problem in THIS ticket is that `EndsDaemon` crashes. it's too late to inform the user. there is no "user" any more. we just need to do something with the job that is already running...

**Comment by original-brownbear** [comment]
@yegor256 right sorry, just figured ...

Ok but in that case I'd say just implement dropping the job and be done with it quietly, we can think about something nicer later?

**Comment by yegor256** [comment]
@original-brownbear oh, yeah, that's a good idea. we should just drop the job and put this stacktrace into the log. so, the job will fail and the user will click on the "log" link and will see the exception stack trace. right?

**Comment by original-brownbear** [comment]
@yegor256 jup that should be doable easily, on it :)

**Comment by yegor256** [comment]
@original-brownbear show me the PR before merging it please

**Comment by original-brownbear** [comment]
@yegor256 sure will link as soon as it's ready here.

**Comment by original-brownbear** [comment]
@yegor256 #1101 something along those lines?, will clean it up with test in 5-10min ...

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is a bug.

@original-brownbear I just added bug tag here

**Comment by sils1297** [comment]
Can't you at least temporary restore services? This is going on for a long time now and we're still waiting on a lot of PRs...

**Comment by alex-palevsky** [comment]
@orthodoc since there is no milestone yet I set it to "2.0"

**Comment by original-brownbear** [comment]
@orthodoc up again, can we close here ? :)

**Comment by orthodoc** [comment]
@original-brownbear I noticed - the commit message following a merge by @rultor seems to be missing the original message and the commit hash. Was that intentional?

**Comment by orthodoc** [comment]
Its better if you responded only to your commanders 😄  ~~@rultor~~ rultor

**Comment by original-brownbear** [comment]
@orthodoc hmm it should not remove messages, what it will do is, that it will add a merge commit message, but the original one should still be there.
Is that the case ?

**Comment by orthodoc** [comment]
@original-brownbear here's a screenshot the build at wercker.

![screen shot 2016-05-20 at 5 47 45 pm](https://cloud.githubusercontent.com/assets/302414/15427523/437757c0-1eb3-11e6-931e-e123dafb49af.png)

Now it says `Merge branch __rultor` instead of the commit message

**Comment by original-brownbear** [comment]
@orthodoc this is expected, you still have all your other commits, but this is the merge commit.
What you can do is use the `rebase: true` setting to avoid the merge commit, if that is something you're interested in?

**Comment by orthodoc** [comment]
@original-brownbear I was wondering as this was not the case earlier. Screenshot below. I am not sure if I use the `--no-ff` flag though. Even if I did it should apply to my commit message and not that of rultor!! I am getting it wrong somewhere. I am closing the issue as this may not be related to the present issue. Cheers!

![screen shot 2016-05-21 at 6 41 31 am](https://cloud.githubusercontent.com/assets/302414/15445587/1db58ad6-1f1f-11e6-9a7c-06c1dae0ad0b.png)
