### ISSUE TITLE
Rultor SSH error

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#1103]
java.io.IOException: com.jcraft.jsch.JSchException: timeout: socket is not established
```
Unfortunately, the system is down, for 4hr already

Please, email this page to bug@rultor.com

java.io.IOException: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcabi.ssh.SSH.session(SSH.java:279)
	at com.jcabi.ssh.SSH.exec(SSH.java:219)
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:103)
	at com.rultor.agents.docker.DockerExec.execute(DockerExec.java:72)
	at com.rultor.spi.SuperAgent$Iterative.execute(SuperAgent.java:76)
	at com.rultor.Routine.process(Routine.java:159)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:275)
	... 21 more
```
http://www.rultor.com/t/8419-220412188

**Comment by jachinte** [comment]
`Unfortunately, the system is down, for 4hr already`

**Comment by original-brownbear** [comment]
@pinaf tried my best to make @yegor256 aware of this now, this needs him unfortunately.

**Comment by original-brownbear** [comment]
@pinaf I think we can close here right ?

**Comment by pinaf** [comment]
@original-brownbear yep, thanks!
