### ISSUE TITLE
XPath bug in EndsDaemon

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1117]
```

com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/talk/daemon/dir/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<talk lat..6699..\uA      <args/>\uA   </request>\uA</talk>': Index (0) is out of bounds (size=0)
	at com.jcabi.xml.ListWrapper.get(ListWrapper.java:154)
	at com.rultor.agents.daemons.EndsDaemon.process(EndsDaemon.java:86)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
```
There is no activity yet, refresh in a few seconds

com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/talk/daemon/dir/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<talk lat..6699..\uA      <args/>\uA   </request>\uA</talk>': Index (0) is out of bounds (size=0)
	at com.jcabi.xml.ListWrapper.get(ListWrapper.java:154)
	at com.rultor.agents.daemons.Script.exec(Script.java:77)
	at com.rultor.agents.daemons.KillsDaemon.process(KillsDaemon.java:79)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```
