### ISSUE TITLE
#description(): thrown java.lang.ClassCastException

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1148]
```
Mar 06 10:39:24 www.rultor.com user: [ERROR] ce7ad22 com.jcabi.github.SmartJson: #value('description', 'interface javax.json.JsonString'): thrown java.lang.ClassCastException(Cannot cast javax.json.JsonValue$1 to javax.json.JsonString) out of java.lang.Class#cast[3186] in 47ms
Mar 06 10:39:24 www.rultor.com user: [ERROR] ce7ad22 com.jcabi.github.SmartJson: #text('description'): thrown java.lang.ClassCastException(Cannot cast javax.json.JsonValue$1 to javax.json.JsonString) out of java.lang.Class#cast[3186] in 48ms
Mar 06 10:39:24 www.rultor.com user: [ERROR] ce7ad22 com.jcabi.github.Repo$Smart: #description(): thrown java.lang.ClassCastException(Cannot cast javax.json.JsonValue$1 to javax.json.JsonString) out of java.lang.Class#cast[3186] in 48ms
Mar 06 10:39:24 www.rultor.com user: [ERROR] ce7ad22 com.rultor.agents.SafeAgent: execute(): com.rultor.agents.hn.HnUpdates throws java.lang.ClassCastException: Cannot cast javax.json.JsonValue$1 to javax.json.JsonString at java.lang.Class.cast(Class.java:3186) at com.jcabi.github.SmartJson.value_aroundBody6(SmartJson.java:143) at com.jcabi.github.SmartJson$AjcClosure7.run(SmartJson.java:1) at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207) at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1) at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136) at com.jcabi.github.SmartJson.value(SmartJson.java:120) at com.jcabi.github.SmartJson.text_aroundBody0(SmartJson.java:81)...
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.62.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.62.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.62.3`

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@rultor version
