### ISSUE TITLE
Branch name problems (invalid)

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/rultor#1190]
looks like Rultor is having problems because of the name of your branch: #251. The PR that has caused this problem can see [here](https://github.com/yegor256/cactoos/pull/252).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1190` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1190` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@filfreire this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1190`, please stop working.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: Can't process this type of notification: {"title":"#354 ignore @0crat assignments","url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","latest_comment_url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","type":"Commit"}
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:103)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: Can't process this type of notification: {"title":"#354 ignore @0crat assignments","url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","latest_comment_url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","type":"Commit"}
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:103)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: Can't process this type of notification: {"title":"#354 ignore @0crat assignments","url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","latest_comment_url":"https://api.github.com/repos/zerocracy/farm/commits/97096402420866657c759a460ed0c282bcb3a555","type":"Commit"}
	at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:103)
	at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
	at com.zerocracy.radars.github.Reaction$Chain.react(Reaction.java:74)
	at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:55)
	at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:65)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1190` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@filfreire resigned from `gh:yegor256/rultor#1190`, please stop working.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/rultor/issues/1190#issuecomment-383536449))

@yegor256 GitHub issue is still open, won't close

**Comment by yegor256** [comment]
@0crat out

**Comment by yegor256** [comment]
@0crat hey

**Comment by 0crat** [comment]
> @0crat hey ([here](https://github.com/yegor256/rultor/issues/1190#issuecomment-383953879))

@yegor256 Hey, what's up, how is it going?

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/rultor/issues/1190#issuecomment-383943934))

@yegor256 The job [#1190](https://github.com/yegor256/rultor/issues/1190) is now out of scope
