### ISSUE TITLE
Problems parsing JSON

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1206]
```
java.lang.AssertionError: HTTP response status is not equal to 205:
400 Bad Request [https://api.github.com/notifications?last_read_at=2017-08-21T13:01:45Z]
Server: GitHub.com
Date: Mon, 21 Aug 2017 13:15:22 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 89
Status: 400 Bad Request
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4427
X-RateLimit-Reset: 1503322207
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user
X-Accepted-OAuth-Scopes: notifications, repo
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-Rack: 0.014355
X-GitHub-Request-Id: 9BE9:24AD8:A89C8F:171395B:599ADCEA

{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3"}
```

**Comment by yegor256** [comment]
temporary bug in GitHub

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 2212f26 2017-08-18T15:01:07
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:yegor256/rultor#1206` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reac...
```
