### ISSUE TITLE
ConcurrentModificationException in TkTicks

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1209]
```
java.util.ConcurrentModificationException: null
    at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:632)
    at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1067)
    at com.rultor.web.TkTicks.dirs(TkTicks.java:127)
    at com.rultor.web.TkTicks.png(TkTicks.java:98)
    at com.rultor.web.TkTicks.act(TkTicks.java:86)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.TkFork.act(TkFork.java:101)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:91)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:81)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:51)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:63)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
    at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:99)
    at org.takes.http.BkBasic.accept(BkBasic.java:77)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:98)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@0crat assign @filfreire

**Comment by 0crat** [comment]
> @0crat assign @filfreire  ([here](https://github.com/yegor256/rultor/issues/1209#issuecomment-324558795))

@yegor256 Job `gh:yegor256/rultor#1209` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @filfreire is not a member of this project yet, but can request to join. @filfreire check your [Zerocracy profile](http://www.0crat.com/u/filfreire) and follow the instructions.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2280](http://www.0crat.com/u/yegor256).

**Comment by filfreire** [comment]
Working on this issue in https://github.com/yegor256/rultor/pull/1210

**Comment by filfreire** [comment]
Solved in PR https://github.com/yegor256/rultor/pull/1210

**Comment by filfreire** [comment]
@yegor256 I believe we can close this issue.

**Comment by yegor256** [comment]
@filfreire thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1209` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @filfreire, total is [+60](http://www.0crat.com/u/filfreire).
