### ISSUE TITLE
Fix StartsRequestITCase

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1211]
Fix test: `StartsRequestITCase.composesCorrectDeployRequest:126 » NodeNotFound XPath 'aut...`

More information:
```
com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath 'author/text()' not found in '<request id="abcd">\uA   <type>deploy</type>\uA   ..84..anch">master</arg>\uA   </args>\uA</request>': Index (0) is out of bounds (size=0)
        at com.jcabi.xml.ListWrapper.get(ListWrapper.java:154)
        at com.rultor.agents.req.StartsRequest.vars(StartsRequest.java:227)
        at com.rultor.agents.req.StartsRequest.script(StartsRequest.java:136)
        at com.rultor.agents.req.StartsRequest.process(StartsRequest.java:106)
        at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
        at com.rultor.agents.req.StartsRequestITCase.composesCorrectDeployRequest(StartsRequestITCase.java:126)
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @filfreire

**Comment by 0crat** [comment]
> @0crat assign @filfreire  ([here](https://github.com/yegor256/rultor/issues/1211#issuecomment-324697732))

@yegor256 Job `gh:yegor256/rultor#1211` assigned to @filfreire, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @filfreire is not a member of this project yet, but can request to join. @filfreire check your [Zerocracy profile](http://www.0crat.com/u/filfreire) and follow the instructions.

**Comment by filfreire** [comment]
Closed related PR https://github.com/yegor256/rultor/pull/1212

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1211` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @filfreire, total is [+30](http://www.0crat.com/u/filfreire).
