### ISSUE TITLE
Add label hacktoberfest to some issues

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1218]
@yegor256 I suggest you pick a few issues from backlog (https://github.com/yegor256/rultor/issues) that have not been assigned to anyone to be solved in the context of https://hacktoberfest.digitalocean.com/

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire good idea, thanks, let me label a few tickets now

**Comment by filfreire** [comment]
@yegor256 closing this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. 1.0-SNAPSHOT 85e7bf1 2017-10-23T11:13:49

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=1, hasQueuedThreads=true, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.io.IOException: java.lang.IllegalStateException: Failed to acquire "claims.xml" in "C3SAYRPH9" in 25s, holdCount=0, queueLength=0, hasQueuedThreads=false, isHeldByCurrentThread=false
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:75)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.item(Claims.java:134)
	at com.zerocracy.pm.Claims.bootstrap(Claims.java:60)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:82)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:59)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13
