### ISSUE TITLE
StartECS todo message issue

### ISSUE THREAD

**Issue by filfreire** [yegor256/rultor#1230]
The StartECS class has the following issues:

```
ERROR: src/main/java/com/rultor/agents/ecs/StartsECS.java; puzzle at line #81; 
@todo must have a leading space to become a puzzle, as this page explains: https://github.com/yegor256/pdd#how-to-format. 
If you can't understand the cause of this issue or you don't know 
how to fix it, please submit a GitHub issue, we will try to help you: https://github.com/yegor256/pdd/issues. This tool is still 
in its beta version and we will appreciate your feedback. 
Here is where you can find more documentation: https://github.com/yegor256/pdd/blob/master/README.md.
```

I fixed this issue on #1222 under commit https://github.com/yegor256/rultor/pull/1222/commits/eb59a0d4a7c08249e95d1a4aae46f7a7d00cb69c

After this commit, another error message is posted on the same class:
```
\u001b[31mERROR\u001b[0m: Puzzle src/main/java/com/rultor/
agents/ecs/StartsECS.java:81-81 has a very short description 
of just 8 words while a minimum of 16 is required
```
This message can be found on https://github.com/yegor256/rultor/pull/1222#issuecomment-352761329

**Comment by filfreire** [comment]
@yegor256 fyi

**Comment by yegor256** [comment]
@filfreire should be fine now

**Comment by filfreire** [comment]
@yegor256 I merged the PRs in master. Can you re-run merge?

**Comment by yegor256** [comment]
@filfreire I think this issue can be closed

**Comment by filfreire** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 0d912b4 2017-12-27T21:47:39
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.value(LengthOf.java:56)
	at org.cactoos.iterable.LengthOf.value(LengthOf.java:56)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.r...
```

Cc @yegor256

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1230` was not in scope
