### ISSUE TITLE
Rultor isn't answering comments

### ISSUE THREAD

**Issue by vssekorin** [yegor256/rultor#1255]
Rultor isn't answering comments.
Here:
- https://github.com/VsSekorin/cactoos-math/pull/186
- https://github.com/VsSekorin/cactoos-math/pull/187

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@VsSekorin we are getting this weird exception for your repo:

```
java.lang.AssertionError: HTTP response status is not equal to 201:
409 Conflict [https://api.github.com/repos/VsSekorin/cactoos-math/contents/.rultor.lock]
Server: GitHub.com
Date: Mon, 23 Apr 2018 17:29:05 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 188
Status: 409 Conflict
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4938
X-RateLimit-Reset: 1524508058
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user
X-Accepted-OAuth-Scopes: 
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-Runtime-Rack: 0.256762
X-GitHub-Request-Id: E67C:66B0:25C020C:58CB4B3:5ADE17E1

{"message":"Could not create file: Required status check \"continuous-integration/travis-ci\" is expected.","documentation_url":"https://help.github.com/articles/about-protected-branches"}
Expected: HTTP response with status 201
     but: was <409 Conflict [https://api.github.com/repos/VsSekorin/cactoos-math/contents/.rultor.lock]
Server: GitHub.com
Date: Mon, 23 Apr 2018 17:29:05 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 188
Status: 409 Conflict
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4938
X-RateLimit-Reset: 1524508058
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user
X-Accepted-OAuth-Scopes: 
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-Runtime-Rack: 0.256762
X-GitHub-Request-Id: E67C:66B0:25C020C:58CB4B3:5ADE17E1

{"message":"Could not create file: Required status check \"continuous-integration/travis-ci\" is expected.","documentation_url":"https://help.github.com/articles/about-protected-branches"}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
	at com.jcabi.github.RtContents.create_aroundBody6(RtContents.java:149)
	at com.jcabi.github.RtContents$AjcClosure7.run(RtContents.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.github.RtContents.create(RtContents.java:143)
	at com.rultor.agents.github.qtn.QnLock.understand(QnLock.java:121)
	at com.rultor.agents.github.qtn.QnIfContains.understand(QnIfContains.java:79)
	at com.rultor.agents.github.qtn.QnFirstOf.understand(QnFirstOf.java:81)
	at com.rultor.agents.github.qtn.QnByArchitect.understand(QnByArchitect.java:107)
	at com.rultor.agents.github.qtn.QnAlone.understand(QnAlone.java:96)
	at com.rultor.agents.github.qtn.QnIfCollaborator.understand(QnIfCollaborator.java:84)
	at com.rultor.agents.github.qtn.QnFirstOf.understand(QnFirstOf.java:81)
	at com.rultor.agents.github.qtn.QnFollow.understand(QnFollow.java:80)
	at com.rultor.agents.github.qtn.QnWithAuthor.understand(QnWithAuthor.java:72)
	at com.rultor.agents.github.qtn.QnParametrized.understand(QnParametrized.java:89)
	at com.rultor.agents.github.qtn.QnReferredTo.understand(QnReferredTo.java:104)
	at com.rultor.agents.github.qtn.QnNotSelf.understand(QnNotSelf.java:75)
	at com.rultor.agents.github.qtn.QnSince.understand(QnSince.java:79)
	at com.rultor.agents.github.qtn.QnSafe.understand(QnSafe.java:72)
	at com.rultor.agents.github.Understands.parse(Understands.java:190)
	at com.rultor.agents.github.Understands.process(Understands.java:130)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:177)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:157)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:152)
	at com.rultor.Routine.run(Routine.java:126)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:748)
```

What do you think this could be?

**Comment by yegor256** [comment]
@VsSekorin looks like you don't allow rultor to commit to master branch. And it is trying to place a lock, which is required for the merge operation.

**Comment by pnatashap** [comment]
@yegor256 @vssekorin looks like the problem was temporary and rultor answered to all messages. issue can be closed

**Comment by yegor256** [comment]
@vssekorin indeed, I'm closing
