### ISSUE TITLE
Sonatype password is visible in logs when settings.xml parsing error has occured

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/rultor#1261]
My `settings.xml` file contained password with ampersand symbol, like this
```xml
<settings>
    <profiles>
        <profile>
            <id>prject/id</id>
            <properties>
                <gpg.homedir>/home/r</gpg.homedir>
                <gpg.keyname>...</gpg.keyname>
                <gpg.passphrase>...</gpg.passphrase>
            </properties>
        </profile>
    </profiles>
    <servers>
        <server>
            <id>oss.sonatype.org</id>
            <username>username</username>
            <password>xxx&</password> <!-- !!! ampersand -->
        </server>
    </servers>
</settings>
```

There is stacktrace with my sonatype password when I'm trying to release:
```
+ mvn clean deploy -Psonatype --errors --settings /home/r/settings.xml
[INFO] Error stacktraces are turned on.
[ERROR] Error executing Maven.
org.apache.maven.settings.building.SettingsBuildingException: 1 problem was encountered while building the effective settings
[FATAL] Non-parseable settings /home/r/settings.xml: entity reference names can not start with character '<' (position: START_TAG seen ...<password>xxx&<... @16:38)  @ /home/r/settings.xml, line 16, column 38

        at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:119)
        at org.apache.maven.cli.configuration.SettingsXmlConfigurationProcessor.process(SettingsXmlConfigurationProcessor.java:137)
        at org.apache.maven.cli.MavenCli.configure(MavenCli.java:1017)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

I changed my password to resolve this, but rultor must hide encrypted files in logs.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@nikialeksey[/z](https://www.0crat.com/u/nikialeksey) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@nikialeksey this is a valid concern, but we can't really do anything with this. It's just a bash script. You should find a way to prevent this from happening somehow, inside your script. Any ideas?

**Comment by nikialeksey** [comment]
May be add some replace processing like logback [replacing](https://logback.qos.ch/manual/layouts.html#replace) on stdout?

**Comment by yegor256** [comment]
@nikialeksey you can simply make your logs invisible: https://doc.rultor.com/reference.html#readers

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1261` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
