### ISSUE TITLE
Rultor is confused after repository rename

### ISSUE THREAD

**Issue by StuporHero** [yegor256/rultor#1262]
I have a private repository which I set up with rultor. I was working on my .rultor.yml config and noticed that I misspelled a word in the name of my repository, so I changed the name of the repository itself to match the correct spelling. This seems to have trapped rultor. Checkout [issue #1](https://github.com/sunsofterp/enterprise-appliance-cookbook/issues/1) to see what I mean (I've already added @yegor256 as a contributor). I'm pretty sure this can be corrected by removing data about this repository, `sunsofterp/enterprise-appliance-cookbook`, and the old repository which was `sunsofterp/enterprise-applicance-cookbook`, but you may also want to consider making rultor resilient to such changes since they do happen from time to time.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@StuporHero it seems that this problem is caused by that, but I'm not sure:

```
java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [392942251] declared for identity constraint of element "talk".
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:110)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:92)
	at com.rultor.dynamo.DyTalk.modify(DyTalk.java:149)
	at com.rultor.cached.CdTalk.modify(CdTalk.java:93)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:177)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:157)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:152)
	at com.rultor.Routine.run(Routine.java:126)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by StuporHero** [comment]
@yegor256 I did notice that every response that I was getting from rultor in that ticket I linked had that same value, but I'm not sure what caused that or what to do about it. I did try talking to him from another ticket, but he did not respond at all.

**Comment by yegor256** [comment]
@StuporHero he is dead now. I'm fixing it... can't understand what's going on, some data duplication.

**Comment by yegor256** [comment]
@rultor release, tag is `1.67.4`

**Comment by yegor256** [comment]
@StuporHero I think it's fixed, can you please check?

**Comment by StuporHero** [comment]
@yegor256 Looks good to me!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
