### ISSUE TITLE
Rultor didn't send answers for messages on PR. And didn't start tasks.

### ISSUE THREAD

**Issue by smallcreep** [yegor256/rultor#1276]
I send rultor messages in this [PR](https://github.com/smallcreep/cucumber-seeds/pull/79) and this [PR](https://github.com/smallcreep/cucumber-seeds/pull/77), but rultor didn't send answers. Before github down 22.10.2018 it's work (ex. [PR](https://github.com/smallcreep/cucumber-seeds/pull/69)). In issue rultor sent answer (ex. [ISSUE-62](https://github.com/smallcreep/cucumber-seeds/issues/62#issuecomment-432158318)).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by smallcreep** [comment]
I get error from [page project on rultor](http://www.rultor.com/p/smallcreep/cucumber-seeds)

```stacktrace
java.lang.IllegalStateException: [GET http://www.rultor.com/p/smallcreep/cucumber-seeds] failed in 303ms: XPath '/talk/wire/href/text()' not found in '\uA\uA   \uA': Index (0) is out of bounds (size=0)
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:101)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/talk/wire/href/text()' not found in '\uA\uA   \uA': Index (0) is out of bounds (size=0)
	at com.jcabi.xml.ListWrapper.get(ListWrapper.java:154)
	at com.rultor.web.TkSiblings.dirs(TkSiblings.java:169)
	at com.rultor.web.TkSiblings.list(TkSiblings.java:150)
	at com.rultor.web.TkSiblings.act(TkSiblings.java:111)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 23 more
```

**Comment by smallcreep** [comment]
@alex-palevsky @yegor256 Please, help me with this problem.

**Comment by smallcreep** [comment]
I find workaround with renaming repository.

**Comment by yegor256** [comment]
@smallcreep This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1276` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
