### ISSUE TITLE
Rultor is out

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/rultor#1282]
Rultor did not responded to my message in https://github.com/yegor256/takes/pull/896#issuecomment-447528253 . [Status page](http://www.rultor.com/status) shows the following error:
```
java.io.IOException: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcabi.ssh.SSH.session(SSH.java:279)
	at com.jcabi.ssh.SSH.exec(SSH.java:219)
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:103)
	at com.rultor.agents.docker.DockerExec.execute(DockerExec.java:72)
	at com.rultor.spi.SuperAgent$Iterative.execute(SuperAgent.java:76)
	at com.rultor.Routine.process(Routine.java:171)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:157)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:152)
	at com.rultor.Routine.run(Routine.java:126)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:275)
	... 21 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@yegor256 Looked like a temporary failure, rultor is up again

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1282` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
