### ISSUE TITLE
Non-parseable settings /home/r/repo/../settings.xml: only whitespace content allowed before start tag and not - (position: START_DOCUMENT seen -... @1:1) 

### ISSUE THREAD

**Issue by dgroup** [yegor256/rultor#1293]
http://www.rultor.com/t/17579-458246862
```bash
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/local/apache-maven/apache-maven-3.3.9/conf/settings.xml
[DEBUG] Reading user settings from /home/r/repo/../settings.xml
[ERROR] Error executing Maven.
org.apache.maven.settings.building.SettingsBuildingException: 1 problem was encountered while building the effective settings
[FATAL] Non-parseable settings /home/r/repo/../settings.xml: only whitespace content allowed before start tag and not - (position: START_DOCUMENT seen -... @1:1)  @ /home/r/repo/../settings.xml, line 1, column 1

        at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:119)
        at org.apache.maven.cli.configuration.SettingsXmlConfigurationProcessor.process(SettingsXmlConfigurationProcessor.java:137)
        at org.apache.maven.cli.MavenCli.configure(MavenCli.java:1017)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
container 2981f00d7f37f0ca645590be7aaa8a33091fd2042830943848c1f2d93221f4ed is dead
Mon Jan 28 19:32:31 CET 2019
```
The `settings.xml` were encrypted using command `rultor encrypt -p dgroup/xxx settings.xml` in accordance with  https://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html
```xml
<settings>
  <servers>
    <server>
      <id>xxx</id>
      <username>xxx</username>
      <privateKey>xxx</privateKey>
    </server>
    <server>
      <id>xxx</id>
      <username>xxx</username>
      <password>xxx</password>
    </server>
  </servers>
  <profiles>
    <profile>
      <id>xxx</id>
      <properties>
        <gpg.executable>xxx</gpg.executable>
        <gpg.passphrase>xxx</gpg.passphrase>
        <gpg.keyname>xxx</gpg.keyname>
      </properties>
    </profile>
    <profile>
      <id>xxx</id>
      <properties>
        <gpg.executable>xxx</gpg.executable>
        <gpg.passphrase>xxx</gpg.passphrase>
        <gpg.keyname>xxx</gpg.keyname>
      </properties>
    </profile>
  </profiles>
</settings>
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3SAYRPH9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by dgroup** [comment]
Similar #899.
The `decrypt` seems is working only with your main repo and can't be used from the external repo.

**Comment by yegor256** [comment]
@dgroup this is weird. It works in a few other projects. Are you sure you are using the right file?

**Comment by yegor256** [comment]
@dgroup you can't decrypt files from another repository. Decrypt only works with files located in _this_ repository. You may want to use `assets`.

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1293` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
