### ISSUE TITLE
No commit found for SHA

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1344]
```
{"message":"No commit found for SHA: ddc795bdbb6e589932c4516c58c6d469b83fc0cc","documentation_url":"https://developer.github.com/v3/repos/commits/#get-a-single-commit"}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
	at com.jcabi.github.RtJson.fetch(RtJson.java:77)
	at com.jcabi.github.RtRepoCommit.json(RtRepoCommit.java:102)
	at com.jcabi.github.SmartJson.json(SmartJson.java:101)
	at com.jcabi.github.RepoCommit$Smart.isVerified(RepoCommit.java:132)
	at com.rultor.profiles.GithubProfile.asset(GithubProfile.java:220)
	at com.rultor.profiles.GithubProfile.assets(GithubProfile.java:141)
	at com.rultor.agents.daemons.StartsDaemon.upload(StartsDaemon.java:184)
	at com.rultor.agents.daemons.StartsDaemon.run_aroundBody0(StartsDaemon.java:150)
	at com.rultor.agents.daemons.StartsDaemon$AjcClosure1.run(StartsDaemon.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.69.1`

**Comment by 0crat** [comment]
Job `gh:yegor256/rultor#1344` is not assigned, can't get performer
