### ISSUE TITLE
There is no 'merge' section in .rultor.yml

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1581]
I have the `.rultor.yml` file in my project in the  `main` branch that actually have correct `merge` section.
[Here is it](https://github.com/volodya-lombrozo/test-naming-conventions/blob/main/.rultor.yml).
Also I have a PR that changes `.rultor.yml` a little bit.
[Here is it](https://github.com/volodya-lombrozo/test-naming-conventions/pull/44).
When I write the message to Rultor: 
> "@rultor merge" 

It gives me [the next exception](https://github.com/volodya-lombrozo/test-naming-conventions/pull/44#issuecomment-1412243122):
```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 245450
+ echo '2.0-SNAPSHOT BUILD'
2.0-SNAPSHOT BUILD
+ date
Wed 01 Feb 2023 04:23:18 PM CET
+ uptime
 16:23:18 up 69 days, 22:01,  0 users,  load average: 0.00, 0.00, 0.00
+ cat
com.rultor.spi.Profile: There is no 'merge' section in .rultor.yml
	at com.rultor.agents.req.StartsRequest.docker(StartsRequest.java:350)
	at com.rultor.agents.req.StartsRequest.vars(StartsRequest.java:255)
	at com.rultor.agents.req.StartsRequest.script(StartsRequest.java:148)
	at com.rultor.agents.req.StartsRequest.process(StartsRequest.java:109)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:70)
	at com.rultor.spi.Agent.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:202)
	at com.rultor.Routine.unsafe_aroundBody0(Routine.java:180)
	at com.rultor.Routine.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.unsafe(Routine.java:175)
	at com.rultor.Routine.run(Routine.java:142)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler.lambda./run.sh(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)

+ exit -1
'cid' file is absent, most probably the Docker container wasn't started correctly
```

Previously I though it was the problem with default branch (The default branch in my case is `main`), but we solved that problem in [that PR](https://github.com/yegor256/rultor/pull/1578).

Where else could be the problem? Can I get more logs from rultor in order to understand the problem?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@volodya-lombrozo I just redeployed again; seems to be a broken deployment last time :(

**Comment by volodya-lombrozo** [comment]
@yegor256 Works like a charm. Thanks!

**Comment by volodya-lombrozo** [comment]
Now we can use Rultor with any other default branch like `main`

**Comment by yegor256** [comment]
@volodya-lombrozo thanks for your help!
