### ISSUE TITLE
Add more informative message for Rultor merge 

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1604]
The issue comes from [that](https://github.com/yegor256/rultor/pull/1600#issuecomment-1432821124) comment.

Rultor logs doesn't contain any useful information about a problem:
```
com.rultor.spi.Profile: There is no 'merge' section in .rultor.yml
	at com.rultor.agents.req.StartsRequest.docker(StartsRequest.java:350)
	at com.rultor.agents.req.StartsRequest.vars(StartsRequest.java:255)
	at com.rultor.agents.req.StartsRequest.script(StartsRequest.java:148)
	at com.rultor.agents.req.StartsRequest.process(StartsRequest.java:109)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:70)
	at com.rultor.spi.Agent.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:202)
	at com.rultor.Routine.unsafe_aroundBody0(Routine.java:180)
	at com.rultor.Routine.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.unsafe(Routine.java:175)
	at com.rultor.Routine.run(Routine.java:142)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler.lambda./run.sh(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It would be nice to add "context" for the error, at least - the branch.

>  Maybe let's make the error message richer? Now it doesn't say which branch it is using to find .rultor.yml. Let's add this info

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you assign it to me, please?

**Comment by yegor256** [comment]
@volodya-lombrozo go ahead=
