### ISSUE TITLE
`StartsRequestTest` fails on Mac

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1613]
Each time when I start to solve a new issue in Rultor I have to disable `com.rultor.agents.req.StartsRequestTest` tests because they are fail. Logs:
```java
java.lang.IllegalArgumentException: Non-zero exit code 1: Initialized empty Git repository in /private/var/f..227..ile changed, 1 insertion(+), 1 deletion(-)\n
	at com.jcabi.log.VerboseProcess.stdout(VerboseProcess.java:298)
	at com.jcabi.log.VerboseProcess.stdout(VerboseProcess.java:185)
	at com.rultor.agents.req.StartsRequestTest.repo(StartsRequestTest.java:512)
	at com.rultor.agents.req.StartsRequestTest.startsDeployRequest(StartsRequestTest.java:111)
```
Almost all tests in `StartsRequestTest` are failed.

OS: 
```
OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"
```

**Comment by volodya-lombrozo** [comment]
Actually it happens because I have different default branch `git config -l`:
```
init.defaultbranch=main
```
