### ISSUE TITLE
`RtChecks` crash during merge phase

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1659]
I've seen the next exception in several places, but I can't understand the reason. Maybe we have to retrieve the full log in order to understand the main cause of the problem.
```java
	at com.jcabi.github.RtChecks.all(RtChecks.java:103)
	at com.rultor.agents.github.qtn.QnMerge.allChecksSuccessful(QnMerge.java:185)
	at com.rultor.agents.github.qtn.QnMerge.understand(QnMerge.java:80)
	at com.rultor.agents.github.qtn.QnIfUnlocked.understand(QnIfUnlocked.java:101)
	at com.rultor.agents.github.qtn.QnIfPull.understand(QnIfPull.java:81)
	at com.rultor.agents.github.qtn.QnAskedBy.understand(QnAskedBy.java:105)
	at com.rultor.agents.github.qtn.QnIfContains.understand(QnIfContains.java:79)
	at com.rultor.agents.github.qtn.QnFirstOf.understand(QnFirstOf.java:81)
	at com.rultor.agents.github.qtn.QnByArchitect.understand(QnByArchitect.java:113)
	at com.rultor.agents.github.qtn.QnAlone.understand(QnAlone.java:96)
	at com.rultor.agents.github.qtn.QnIfCollaborator.understand(QnIfCollaborator.java:84)
	at com.rultor.agents.github.qtn.QnFirstOf.understand(QnFirstOf.java:81)
	at com.rultor.agents.github.qtn.QnFollow.understand(QnFollow.java:85)
	at com.rultor.agents.github.qtn.QnWithAuthor.understand(QnWithAuthor.java:72)
	at com.rultor.agents.github.qtn.QnParametrized.understand(QnParametrized.java:89)
	at com.rultor.agents.github.qtn.QnReaction.understand(QnReaction.java:96)
	at com.rultor.agents.github.qtn.QnReferredTo.understand(QnReferredTo.java:104)
	at com.rultor.agents.github.qtn.QnNotSelf.understand(QnNotSelf.java:75)
	at com.rultor.agents.github.qtn.QnSince.understand(QnSince.java:79)
	at com.rultor.agents.github.qtn.QnSafe.understand(QnSafe.java:75)
	at com.rultor.agents.github.Understands.parse(Understands.java:197)
	at com.rultor.agents.github.Understands.process(Understands.java:131)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:70)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:202)
	at com.rultor.Routine.unsafe_aroundBody0(Routine.java:180)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.unsafe(Routine.java:175)
	at com.rultor.Routine.run(Routine.java:142)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler$Service.lambda$0(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by h1alexbel** [comment]
@volodya-lombrozo same

**Comment by yegor256** [comment]
@volodya-lombrozo we should fix Rultor so that it prints the exception message inside this GitHub message. Now it doesn't print it, for some reason (the top line is missing). Maybe you can fix this?

**Comment by volodya-lombrozo** [comment]
@yegor256 sure

**Comment by volodya-lombrozo** [comment]
Blocked by https://github.com/jcabi/jcabi-github/pull/1625

**Comment by l3r8yJ** [comment]
@volodya-lombrozo what is the status of this issue?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ As far as I know everything works fine.

**Comment by l3r8yJ** [comment]
@volodya-lombrozo yes, it seems to be fixed, the issue can be closed
