### ISSUE TITLE
Can't merge into `main` branch. 

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1664]
When I'm trying to merge something into `main` branch I get the next exception:
```
404 Not Found [https://api.github.com/repos/volodya-lombrozo/jtcop/contents/.rultor.yml?ref=master]
Server: GitHub.com
Date: Mon, 27 Mar 2023 16:45:21 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user, workflow
X-Accepted-OAuth-Scopes: 
X-GitHub-Media-Type: github.v3
X-Github-Api-Version-Selected: 2022-11-28
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4717
X-RateLimit-Reset: 1679938419
X-RateLimit-Used: 283
X-RateLimit-Resource: core
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: D120:74CF:5FB528:C411F6:6421C821

{"message":"No commit found for the ref master","documentation_url":"https://docs.github.com/v3/repos/contents/"}
Expected: HTTP response with status 200
     but: was <404 Not Found [https://api.github.com/repos/volodya-lombrozo/jtcop/contents/.rultor.yml?ref=master]
Server: GitHub.com
Date: Mon, 27 Mar 2023 16:45:21 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
X-OAuth-Scopes: admin:org, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user, workflow
X-Accepted-OAuth-Scopes: 
X-GitHub-Media-Type: github.v3
X-Github-Api-Version-Selected: 2022-11-28
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4717
X-RateLimit-Reset: 1679938419
X-RateLimit-Used: 283
X-RateLimit-Resource: core
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: D120:74CF:5FB528:C411F6:6421C821

{"message":"No commit found for the ref master","documentation_url":"https://docs.github.com/v3/repos/contents/"}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:109)
	at com.jcabi.github.RtContents.content(RtContents.java:260)
	at com.jcabi.github.RtContents.get(RtContents.java:174)
	at com.rultor.profiles.GithubProfile.yml(GithubProfile.java:310)
	at com.rultor.profiles.GithubProfile.read(GithubProfile.java:136)
	at com.rultor.agents.github.qtn.QnByArchitect.understand(QnByArchitect.java:106)
	at com.rultor.agents.github.qtn.QnAlone.understand(QnAlone.java:96)
	at com.rultor.agents.github.qtn.QnIfCollaborator.understand(QnIfCollaborator.java:84)
	at com.rultor.agents.github.qtn.QnFirstOf.understand(QnFirstOf.java:81)
	at com.rultor.agents.github.qtn.QnFollow.understand(QnFollow.java:85)
	at com.rultor.agents.github.qtn.QnWithAuthor.understand(QnWithAuthor.java:72)
	at com.rultor.agents.github.qtn.QnParametrized.understand(QnParametrized.java:89)
	at com.rultor.agents.github.qtn.QnReaction.understand(QnReaction.java:96)
	at com.rultor.agents.github.qtn.QnReferredTo.understand(QnReferredTo.java:104)
	at com.rultor.agents.github.qtn.QnNotSelf.understand(QnNotSelf.java:75)
	at com.rultor.agents.github.qtn.QnSince.understand(QnSince.java:79)
	at com.rultor.agents.github.qtn.QnSafe.understand(QnSafe.java:75)
	at com.rultor.agents.github.Understands.parse(Understands.java:197)
	at com.rultor.agents.github.Understands.process(Understands.java:131)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:70)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:202)
	at com.rultor.Routine.unsafe_aroundBody0(Routine.java:180)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.unsafe(Routine.java:175)
	at com.rultor.Routine.run(Routine.java:142)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler$Service.lambda$0(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It happened in several repositories:
- at least [here](https://github.com/volodya-lombrozo/jtcop/pull/79)
- and [here](https://github.com/volodya-lombrozo/rultor-main-branch-test/pull/2)

**Comment by volodya-lombrozo** [comment]
@yegor256 Maybe you deployed an old version of Rultor?

**Comment by yegor256** [comment]
@volodya-lombrozo this is the latest one

**Comment by volodya-lombrozo** [comment]
@yegor256 Hm... Looks strange. I will investigate it then.
