### ISSUE TITLE
`ClassCastException` during CI checks validation

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/rultor#1678]
Sometimes instead of printing correct message:
> Can't merge it. Some CI checks were failed. Apparently, the pull request is not ready to be merged since it has some problems. Please, fix them first.

Rultor throw an exception `ClassCastException`:
```java
java.lang.ClassCastException: class javax.json.JsonValueImpl cannot be cast to class javax.json.JsonString (javax.json.JsonValueImpl and javax.json.JsonString are in unnamed module of loader 'app')
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.jcabi.github.RtChecks.check(RtChecks.java:127)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.jcabi.github.RtChecks.lambda$all$0(RtChecks.java:113)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.jcabi.github.RtChecks.all(RtChecks.java:110)
	at com.rultor.agents.github.qtn.QnMerge.allChecksSuccessful(QnMerge.java:185)
	at com.rultor.agents.github.qtn.QnMerge.understand(QnMerge.java:80)
	at com.rultor.agents.github.qtn.QnIfUnlocked.understand(QnIfUnlocked.java:101)
	at com.rultor.agents.github.qtn.QnIfPull.understand(QnIfPull.java:81)
	at com.rultor.agents.github.qtn.QnAskedBy.understand(QnAskedBy.java:105)
	at com.rultor.agents.github.qtn.QnIfContains.understand(QnIfContains.java:79)
	at com.rultor.agents.github.qtn.QnFirstOf.understand(QnFirstOf.java:81)
	at com.rultor.agents.github.qtn.QnByArchitect.understand(QnByArchitect.java:113)
	at com.rultor.agents.github.qtn.QnAlone.understand(QnAlone.java:96)
	at com.rultor.agents.github.qtn.QnIfCollaborator.understand(QnIfCollaborator.java:84)
	at com.rultor.agents.github.qtn.QnFirstOf.understand(QnFirstOf.java:81)
	at com.rultor.agents.github.qtn.QnFollow.understand(QnFollow.java:85)
	at com.rultor.agents.github.qtn.QnWithAuthor.understand(QnWithAuthor.java:72)
	at com.rultor.agents.github.qtn.QnParametrized.understand(QnParametrized.java:89)
	at com.rultor.agents.github.qtn.QnReaction.understand(QnReaction.java:96)
	at com.rultor.agents.github.qtn.QnReferredTo.understand(QnReferredTo.java:104)
	at com.rultor.agents.github.qtn.QnNotSelf.understand(QnNotSelf.java:75)
	at com.rultor.agents.github.qtn.QnSince.understand(QnSince.java:79)
	at com.rultor.agents.github.qtn.QnSafe.understand(QnSafe.java:82)
	at com.rultor.agents.github.Understands.parse(Understands.java:197)
	at com.rultor.agents.github.Understands.process(Understands.java:131)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:70)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:84)
	at com.rultor.Routine.process(Routine.java:202)
	at com.rultor.Routine.unsafe_aroundBody0(Routine.java:180)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:108)
	at com.rultor.Routine.unsafe(Routine.java:175)
	at com.rultor.Routine.run(Routine.java:142)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at com.jcabi.aspects.aj.MethodScheduler$Service.lambda$0(MethodScheduler.java:194)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:222)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Pipeline example: https://github.com/objectionary/eo/pull/1976

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you assign it to me, please?
