### ISSUE TITLE
java.util.EmptyStackException

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1871]
I see this in rultor.com:

```
java.lang.IllegalStateException: [GET https://www.rultor.com/] failed in 35s: NULL
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:232)
	at org.takes.facets.fallback.TkFallback.fallback(TkFallback.java:138)
	at org.takes.facets.fallback.TkFallback.lambda$wrap$2(TkFallback.java:197)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsGzip.make(RsGzip.java:88)
	at org.takes.rs.RsGzip.head(RsGzip.java:69)
	at org.takes.facets.fork.RsFork.lambda$new$0(RsFork.java:66)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.head(ResponseOf.java:81)
	at org.takes.rs.RsWrap.head(RsWrap.java:58)
	at org.takes.rs.RsWithHeader.lambda$new$1(RsWithHeader.java:114)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.head(ResponseOf.java:81)
	at org.takes.rs.RsWrap.head(RsWrap.java:58)
	at org.takes.rs.RsWithHeader.lambda$new$1(RsWithHeader.java:114)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.head(ResponseOf.java:81)
	at org.takes.rs.RsWrap.head(RsWrap.java:58)
	at org.takes.rs.RsWithHeader.lambda$new$1(RsWithHeader.java:114)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.head(ResponseOf.java:81)
	at org.takes.rs.RsWrap.head(RsWrap.java:58)
	at org.takes.rs.RsWithHeaders.extend(RsWithHeaders.java:89)
	at org.takes.rs.RsWithHeaders.lambda$new$0(RsWithHeaders.java:69)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.head(ResponseOf.java:81)
	at org.takes.rs.RsWrap.head(RsWrap.java:58)
	at org.takes.rs.RsWrap.head(RsWrap.java:58)
	at org.takes.rs.RsPrint.printHead(RsPrint.java:132)
	at org.takes.rs.RsPrint.print(RsPrint.java:117)
	at org.takes.http.BkBasic.print(BkBasic.java:123)
	at org.takes.http.BkBasic.accept(BkBasic.java:99)
	at org.takes.http.BkSafe.lambda$new$0(BkSafe.java:46)
	at org.takes.http.BkWrap.accept(BkWrap.java:51)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:92)
	at org.takes.http.BkParallel.lambda$new$0(BkParallel.java:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:182)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:401)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:170)
	at com.jcabi.dynamo.AwsTable.keys(AwsTable.java:158)
	at com.jcabi.dynamo.AwsFrame.iterator_aroundBody2(AwsFrame.java:125)
	at com.jcabi.dynamo.AwsFrame$AjcClosure3.run(AwsFrame.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:179)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:135)
	at com.jcabi.dynamo.AwsFrame.iterator(AwsFrame.java:120)
	at com.jcabi.dynamo.retry.ReFrame.iterator_aroundBody32(ReFrame.java:124)
	at com.jcabi.dynamo.retry.ReFrame$AjcClosure33.run(ReFrame.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:183)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:135)
	at com.jcabi.dynamo.retry.ReFrame.iterator_aroundBody34(ReFrame.java:124)
	at com.jcabi.dynamo.retry.ReFrame$AjcClosure35.run(ReFrame.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:183)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
	at com.jcabi.dynamo.retry.ReFrame.iterator(ReFrame.java:124)
	at org.cactoos.iterable.Mapped.lambda$new$0(Mapped.java:61)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.Filtered.lambda$new$0(Filtered.java:71)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.HeadOf.lambda$new$0(HeadOf.java:56)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.Mapped.lambda$new$0(Mapped.java:61)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at org.cactoos.iterable.HeadOf.lambda$new$0(HeadOf.java:56)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.iterable.IterableOf.iterator(IterableOf.java:83)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:53)
	at com.rultor.web.TkHome.recent(TkHome.java:97)
	at org.takes.rs.xe.XeChain.lambda$new$1(XeChain.java:70)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:55)
	at org.takes.rs.xe.XeChain.lambda$new$1(XeChain.java:70)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:55)
	at org.takes.rs.xe.XeAppend.lambda$new$0(XeAppend.java:69)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:55)
	at org.takes.rs.xe.XeChain.lambda$new$1(XeChain.java:70)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:55)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:136)
	at org.takes.rs.xe.RsXembly.lambda$new$1(RsXembly.java:119)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsXslt.lambda$new$0(RsXslt.java:113)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:119)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:105)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.takes.rs.ResponseOf.body(ResponseOf.java:86)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.rs.RsWrap.body(RsWrap.java:63)
	at org.takes.facets.fallback.TkFallback.lambda$wrap$2(TkFallback.java:185)
	... 47 more
```

**Comment by yegor256** [comment]
@pnatashap maybe you can help? I suspect this is related to the recent changes we've made, but not sure. Maybe it would be better to [upgrade](https://github.com/yegor256/rultor/pull/1712) to jcabi-aspects 0.25.1 first?

**Comment by pnatashap** [comment]
@yegor256  Version is updated, but as I can see the aspectjrt in jcabi-aspects is 1.9.19 (on compile time), but I have faced with a lot of different issues in case of different versions were used and the error was absolutely meaning less.
So may be try to run with this change, may be downgrade aspectjrt to 1.9.19 is also good idea. (will create an additional PR)
Will create a PR to jcabi-aspects to update aspectjrt

**Comment by yegor256** [comment]
@pnatashap seems to be fixed now, thanks!
