### ISSUE TITLE
StartsRequestTest sometimes fails

### ISSUE THREAD

**Issue by krzyk** [yegor256/rultor#635]
StartsRequestTest when it fails:
```
[WARN] com.jcabi.log.VerboseProcess: >> + (( i++  ))
[WARN] com.jcabi.log.VerboseProcess: >> + (( i<=4 ))
[WARN] com.jcabi.log.VerboseProcess: >> + cd repo
[WARN] com.jcabi.log.VerboseProcess: >> + git tag 1.0-beta -m '1.0-beta: tagged by rultor.com'
[WARN] com.jcabi.log.VerboseProcess: >> + git push origin 1.0-beta
[WARN] com.jcabi.log.VerboseProcess: >> To /tmp/junit572435416425594115/junit6846409826810492500
[WARN] com.jcabi.log.VerboseProcess: >>  * [new tag]         1.0-beta -> 1.0-beta
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 131.258 sec <<< FAILURE! - in com.rultor.agents.req.StartsRequestTest
startsMergeRequest(com.rultor.agents.req.StartsRequestTest)  Time elapsed: 121.536 sec  <<< ERROR!
java.lang.IllegalArgumentException: Non-zero exit code 2: + set -e\n+ set -o pipefail\n+ head=/tmp/junit249669..973.. keyserver receive failed: keyserver error\n
	at com.jcabi.log.VerboseProcess.stdout(VerboseProcess.java:220)
	at com.jcabi.log.VerboseProcess.stdout(VerboseProcess.java:158)
	at com.rultor.agents.req.StartsRequestTest.exec(StartsRequestTest.java:321)
	at com.rultor.agents.req.StartsRequestTest.startsMergeRequest(StartsRequestTest.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
```

**Comment by krzyk** [comment]
@dpisarenko Sorry for late reply, I think the best would be to use standard java system settings, this way it is consistent with java system libraries. It would work for: `java -Dhttp.proxyHost=proxy.server -Dhttp.proxyPort=80` or `mvn -Dhttp.proxyHost=proxy.server -Dhttp.proxyPort=80 clean install -Pqulice`

**Comment by dpisarenko** [comment]
@krzyk I modified the pull request so that now the proxy settings are read from system properties, as you suggested.

**Comment by alex-palevsky** [comment]
@dpisarenko you're holding this task for 7 days already

added -5 to your rating, now it is equal to [+155](http://www.netbout.com/b/35089?open=rating)

**Comment by alex-palevsky** [comment]
@dpisarenko please don't touch this task, someone else will pick it up, thanks

**Comment by alex-palevsky** [comment]
@maurezen This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by maurezen** [comment]
Note: I don't have an environment to reproduce.

Created a pull request here #717

**Comment by maurezen** [comment]
@krzyk pull request #717 merged to master, please close the issue.

**Comment by alex-palevsky** [comment]
@maurezen Much appreciated! **30 mins** was added to your account, payment ID `50264727`... +30 added to your rating, at the moment it is: [+450](http://www.netbout.com/b/35102?open=rating)
