### ISSUE TITLE
Incomplete documentation: Prerequisites for running Rultor tests

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/rultor#686]
Please provide a short description of what must be done on a Windows machine prior to successfully running the Rultor tests.

Currently, the attempt to run com.rultor.agents.req.StartsRequestTest results in errors like

```
java.lang.IllegalStateException: java.io.IOException: Cannot run program "/bin/bash" (in directory "C:\Users\DP118M\AppData\Local\Temp\junit4189229655716590509\junit4190078941092721"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at com.jcabi.log.VerboseProcess.start(VerboseProcess.java:193)
	at com.jcabi.log.VerboseProcess.<init>(VerboseProcess.java:106)
	at com.rultor.agents.req.StartsRequestTest.repo(StartsRequestTest.java:439)
	at com.rultor.agents.req.StartsRequestTest.startsMergeRequest(StartsRequestTest.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:202)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.io.IOException: Cannot run program "/bin/bash" (in directory "C:\Users\DP118M\AppData\Local\Temp\junit4189229655716590509\junit4190078941092721"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
	at com.jcabi.log.VerboseProcess.start(VerboseProcess.java:189)
	... 31 more
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
	... 32 more
```

`mvn install` results in various test failures (27 errors).

**Comment by alex-palevsky** [comment]
@jenya the ticket is with you for 9 days already. If it's not finished in the next 16 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. added -5 to your rating, now it is equal to [-10](http://www.netbout.com/b/35092?open=rating)

**Comment by yegor256** [comment]
@dmarkov please assign someone else

**Comment by alex-palevsky** [comment]
@jenya it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is [-225](http://www.netbout.com/b/35092?open=rating)

**Comment by alex-palevsky** [comment]
@palyuga please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by palyuga** [comment]
@dpisarenko are you able to make it work on Windows? I've tried a couple of bash implementations for Windows (cygwin and win-bash) and they can't run the test correctly, parameter substitution doesn't work like in native bash. 
In case we don't know how to solve this issue, maybe just ignoring this test for Windows platform will be enough?

**Comment by dpisarenko** [comment]
@palyuga No, it doesn't work on Windows using cygwin (tried that as well).

There are 2 workarounds I tested:

  1. Use Ubuntu Server inside Virtual box (modify source under Window, push changes to GitHub, pull changes inside the Ubuntu VM, run `mvn install -Pqulice` there).
  1. Run `mvn qulice:check -Pqulice` on the local machine and check the results of `mvn install -Pqulice` in Travis CI (i. e. instead of running `mvn install -Pqulice` on the Windows machine, push the changes to Gihub, then look at Travis CI log).

Both of these options are not very comfortable. Option 1 suffers from inability to copy/paste text between Windows and Ubuntu (and there is no easy fix, tried that).

Option 2 takes a lot of time.

**Comment by dpisarenko** [comment]
@palyuga Another option is to use Digital Ocean, but I'm not sure that the small (5 bucks) droplet is sufficient for running `mvn install -Pqulice` without getting OutOfMemory errors.

**Comment by palyuga** [comment]
@dpisarenko pull request is merged now, check and close this issue, please

**Comment by alex-palevsky** [comment]
@palyuga Thanks for your contribution, **30 mins** was added to your account, payment ID is `50305731`

+30 to your rating, your total score is +165
