### ISSUE TITLE
build failed under OS X

### ISSUE THREAD

**Issue by apocarteres** [yegor256/rultor#701]
Environments:
<code>
$ MAVEN_OPTS="-Xms1g -Xmx1g -XX:MaxPermSize=256m" mvn --version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 22:22:22+0700)
Maven home: /opt/apache-maven-3.1.1
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
</code>

Clear repo checkout (head on commit 010def897af0052147785688f27bc138b69a2e6f), try to build with command:
<code>
MAVEN_OPTS="-Xms1g -Xmx1g -XX:MaxPermSize=256m" mvn -T 8 -e clean install -Pqulice
</code>

build process ran into exception:
<pre>
Downloading: http://repo.maven.apache.org/maven2/com/yahoo/platform/yui/yuicompressor/2.4.7/yuicompressor-2.4.7.jar
Downloading: http://repo.maven.apache.org/maven2/args4j/args4j/2.0.16/args4j-2.0.16.jar
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Downloaded: http://repo.maven.apache.org/maven2/args4j/args4j/2.0.16/args4j-2.0.16.jar (55 KB at 90.6 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar (165 KB at 187.7 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/com/yahoo/platform/yui/yuicompressor/2.4.7/yuicompressor-2.4.7.jar (871 KB at 826.5 KB/sec)
[WARNING] Error injecting: com.samaxes.maven.minify.plugin.MinifyMojo
java.lang.TypeNotPresentException: Type com.samaxes.maven.minify.plugin.MinifyMojo not present
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:115)
	at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:459)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:97)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:169)
	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:165)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
</pre>

**Comment by yegor256** [comment]
@apocarteres hm... I can't reproduce this problem. try to run again, you still see the same exception?

**Comment by apocarteres** [comment]
yes. it still takes a place.

<pre>
[INFO] Unpacking /Users/sandro/.m2/repository/com/jcabi/DynamoDBLocal/2014-01-08/DynamoDBLocal-2014-01-08.zip to /Users/sandro/work/odesk/rultor/target/dynamodb-dist with includes "" and excludes ""
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create (jcabi-build-number) @ rultor ---
[INFO] ShortRevision tag detected. The value is '7'.
[INFO] Executing: /bin/sh -c cd /Users/sandro/work/odesk/rultor && git rev-parse --verify --short=7 HEAD
[INFO] Working directory: /Users/sandro/work/odesk/rultor
[INFO] Storing buildNumber: 010def8 at timestamp: 2015-01-05T13:26:21
[INFO] Storing buildScmBranch: master
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.3:create-timestamp (jcabi-build-number) @ rultor ---
[INFO] 
[INFO] --- sass-maven-plugin:1.1.1:update-stylesheets (generate-css) @ rultor ---
[INFO] Compiling SASS Templates
[INFO] Queing SASS Template for compile: /Users/sandro/work/odesk/rultor/src/main/scss => /Users/sandro/work/odesk/rultor/target/css
[INFO]     >> /Users/sandro/work/odesk/rultor/src/main/scss/main.scss => /Users/sandro/work/odesk/rultor/target/css/main.css
[INFO]     >> /Users/sandro/work/odesk/rultor/src/main/scss/siblings.scss => /Users/sandro/work/odesk/rultor/target/css/siblings.css
[INFO] 
[INFO] --- htmlcompressor-maven-plugin:1.3:xml (compress-xsl) @ rultor ---
[INFO] Compressing /Users/sandro/work/odesk/rultor/src/main/webapp/xsl
[INFO] XML compression completed.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rultor ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 22 resources
[INFO] 
[INFO] --- minify-maven-plugin:1.7.2:minify (minify-js) @ rultor ---
[WARNING] Error injecting: com.samaxes.maven.minify.plugin.MinifyMojo
java.lang.TypeNotPresentException: Type com.samaxes.maven.minify.plugin.MinifyMojo not present
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:115)
	at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:459)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:97)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.UnsupportedClassVersionError: com/samaxes/maven/minify/plugin/MinifyMojo : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:242)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:107)
	... 41 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.614s
[INFO] Finished at: Mon Jan 05 13:26:25 NOVT 2015
[INFO] Final Memory: 27M/1011M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.2:minify (minify-js) on project rultor: Execution minify-js of goal com.samaxes.maven:minify-maven-plugin:1.7.2:minify failed: Unable to load the mojo 'minify' in the plugin 'com.samaxes.maven:minify-maven-plugin:1.7.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/samaxes/maven/minify/plugin/MinifyMojo : Unsupported major.minor version 51.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.samaxes.maven:minify-maven-plugin:1.7.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/sandro/.m2/repository/com/samaxes/maven/minify-maven-plugin/1.7.2/minify-maven-plugin-1.7.2.jar
[ERROR] urls[1] = file:/Users/sandro/.m2/repository/com/yahoo/platform/yui/yuicompressor/2.4.7/yuicompressor-2.4.7.jar
[ERROR] urls[2] = file:/Users/sandro/.m2/repository/rhino/js/1.6R7/js-1.6R7.jar
[ERROR] urls[3] = file:/Users/sandro/.m2/repository/com/google/javascript/closure-compiler/v20130823/closure-compiler-v20130823.jar
[ERROR] urls[4] = file:/Users/sandro/.m2/repository/args4j/args4j/2.0.16/args4j-2.0.16.jar
[ERROR] urls[5] = file:/Users/sandro/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar
[ERROR] urls[6] = file:/Users/sandro/.m2/repository/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar
[ERROR] urls[7] = file:/Users/sandro/.m2/repository/org/json/json/20090211/json-20090211.jar
[ERROR] urls[8] = file:/Users/sandro/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[9] = file:/Users/sandro/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.rultor:rultor:2.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.2:minify (minify-js) on project rultor: Execution minify-js of goal com.samaxes.maven:minify-maven-plugin:1.7.2:minify failed: Unable to load the mojo 'minify' in the plugin 'com.samaxes.maven:minify-maven-plugin:1.7.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/samaxes/maven/minify/plugin/MinifyMojo : Unsupported major.minor version 51.0
-----------------------------------------------------
realm =    plugin>com.samaxes.maven:minify-maven-plugin:1.7.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/sandro/.m2/repository/com/samaxes/maven/minify-maven-plugin/1.7.2/minify-maven-plugin-1.7.2.jar
urls[1] = file:/Users/sandro/.m2/repository/com/yahoo/platform/yui/yuicompressor/2.4.7/yuicompressor-2.4.7.jar
urls[2] = file:/Users/sandro/.m2/repository/rhino/js/1.6R7/js-1.6R7.jar
urls[3] = file:/Users/sandro/.m2/repository/com/google/javascript/closure-compiler/v20130823/closure-compiler-v20130823.jar
urls[4] = file:/Users/sandro/.m2/repository/args4j/args4j/2.0.16/args4j-2.0.16.jar
urls[5] = file:/Users/sandro/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar
urls[6] = file:/Users/sandro/.m2/repository/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar
urls[7] = file:/Users/sandro/.m2/repository/org/json/json/20090211/json-20090211.jar
urls[8] = file:/Users/sandro/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
urls[9] = file:/Users/sandro/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[project>com.rultor:rultor:2.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

-----------------------------------------------------

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution minify-js of goal com.samaxes.maven:minify-maven-plugin:1.7.2:minify failed: Unable to load the mojo 'minify' in the plugin 'com.samaxes.maven:minify-maven-plugin:1.7.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/samaxes/maven/minify/plugin/MinifyMojo : Unsupported major.minor version 51.0
-----------------------------------------------------
realm =    plugin>com.samaxes.maven:minify-maven-plugin:1.7.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/sandro/.m2/repository/com/samaxes/maven/minify-maven-plugin/1.7.2/minify-maven-plugin-1.7.2.jar
urls[1] = file:/Users/sandro/.m2/repository/com/yahoo/platform/yui/yuicompressor/2.4.7/yuicompressor-2.4.7.jar
urls[2] = file:/Users/sandro/.m2/repository/rhino/js/1.6R7/js-1.6R7.jar
urls[3] = file:/Users/sandro/.m2/repository/com/google/javascript/closure-compiler/v20130823/closure-compiler-v20130823.jar
urls[4] = file:/Users/sandro/.m2/repository/args4j/args4j/2.0.16/args4j-2.0.16.jar
urls[5] = file:/Users/sandro/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar
urls[6] = file:/Users/sandro/.m2/repository/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar
urls[7] = file:/Users/sandro/.m2/repository/org/json/json/20090211/json-20090211.jar
urls[8] = file:/Users/sandro/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
urls[9] = file:/Users/sandro/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[project>com.rultor:rultor:2.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:120)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'minify' in the plugin 'com.samaxes.maven:minify-maven-plugin:1.7.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/samaxes/maven/minify/plugin/MinifyMojo : Unsupported major.minor version 51.0
-----------------------------------------------------
realm =    plugin>com.samaxes.maven:minify-maven-plugin:1.7.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/Users/sandro/.m2/repository/com/samaxes/maven/minify-maven-plugin/1.7.2/minify-maven-plugin-1.7.2.jar
urls[1] = file:/Users/sandro/.m2/repository/com/yahoo/platform/yui/yuicompressor/2.4.7/yuicompressor-2.4.7.jar
urls[2] = file:/Users/sandro/.m2/repository/rhino/js/1.6R7/js-1.6R7.jar
urls[3] = file:/Users/sandro/.m2/repository/com/google/javascript/closure-compiler/v20130823/closure-compiler-v20130823.jar
urls[4] = file:/Users/sandro/.m2/repository/args4j/args4j/2.0.16/args4j-2.0.16.jar
urls[5] = file:/Users/sandro/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar
urls[6] = file:/Users/sandro/.m2/repository/com/google/protobuf/protobuf-java/2.4.1/protobuf-java-2.4.1.jar
urls[7] = file:/Users/sandro/.m2/repository/org/json/json/20090211/json-20090211.jar
urls[8] = file:/Users/sandro/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
urls[9] = file:/Users/sandro/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[project>com.rultor:rultor:2.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

-----------------------------------------------------

	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:489)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:97)
	... 20 more
Caused by: java.lang.UnsupportedClassVersionError: com/samaxes/maven/minify/plugin/MinifyMojo : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:389)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:242)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:107)
	at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:55)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.eclipse.sisu.plexus.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:997)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1047)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:993)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:82)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:260)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:252)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:459)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
</pre>

**Comment by yegor256** [comment]
looks like we have to upgrade to 1.7 and make this version mandatory.

**Comment by alex-palevsky** [comment]
@maurezen this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by alex-palevsky** [comment]
@apocarteres thank you for the ticket reported, I topped your account for 15 mins, transaction `49764309`

**Comment by maurezen** [comment]
@apocarteres pull request merged and closed, please close the issue now.

**Comment by apocarteres** [comment]
yeah. looks like the issue is gone now. thank you

**Comment by alex-palevsky** [comment]
@maurezen Many thanks! **30 mins** were added to your account in Transaction ID `50000661`... +30 to your rating, your total score is [+210](http://www.netbout.com/b/35102?open=rating)
