### ISSUE TITLE
build fails if your locale is not en_US

### ISSUE THREAD

**Issue by wentwog** [yegor256/rultor#707]
```
mvn clean install 
```
fails with
```
reportsRequestResult(com.rultor.agents.github.ReportsTest)  Time elapsed: 0.424 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
        at com.rultor.agents.github.ReportsTest.reportsRequestResult(ReportsTest.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.MissingResourceException: Can't find bundle for base name phrases, locale ru_RU
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
        at com.rultor.agents.github.Reports.<clinit>(Reports.java:64)
        ... 19 more
```

There are other issues that fail the build but the current ticket is only about the specified issue.

I suggest to add this to pom.xml:
```
<plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                        <argLine>-Duser.language=en -Duser.region=US</argLine>
                    </configuration>
                </plugin>
```

Setting MAVEN_OPTS doesn't help.

I can myself provide a PL since I've already tested it, but it depends on who will be assigned to the ticket.

**Comment by alex-palevsky** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by alex-palevsky** [comment]
@oruam85 This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here. Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by alex-palevsky** [comment]
@wentwog thanks for the ticket, your account was topped for 15 mins, payment 49750983

**Comment by oruam85** [comment]
This is the PR https://github.com/yegor256/rultor/pull/729

**Comment by oruam85** [comment]
@alex-palevsky  This bug is already merged. Please close

**Comment by alex-palevsky** [comment]
@oruam85 you are holding this task for 11 days already; -30 added to your rating, current score is: +90

**Comment by oruam85** [comment]
@alex-palevsky why? the PR was merged 13 hours ago

**Comment by yegor256** [comment]
@oruam85 PR merging doesn't mean ticket closing. You should make sure the ticket is closed by @wentwog. See http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#2.-close-it!

**Comment by oruam85** [comment]
@yegor256 Yes, but if you see the message above can check the status. @wentwog the PR was merged 1 day ago. Can you check this and close this bugs?

**Comment by wentwog** [comment]
@oruam85 thank you.

**Comment by oruam85** [comment]
@alex-palevsky i am waiting for the payment. Thanks

**Comment by alex-palevsky** [comment]
@oruam85 Much obliged! I've added **30 mins** to your account in payment "50331024"

+30 added to your rating, at the moment it is: +120
