### ISSUE TITLE
NumberFormatException: For input string: "" 	

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#709]
```
[WARN] 3abd9ae com.jcabi.log.VerboseRunnable: swallowed exception: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.NumberFormatException: For input string: "" 	
at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:139) 	
at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198) 	
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 	
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) 	
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) 
at:  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 	
at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220) 	
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.lang.IllegalStateException: java.lang.NumberFormatException: For input string: "" 	
at com.rultor.web.Lifespan.uninterrupted(Lifespan.java:175) 	
at com.rultor.web.Lifespan.access$000(Lifespan.java:  86) 	
at com.rultor.web.Lifespan$1.call(Lifespan.java:128) 	
at com.rultor.web.Lifespan$1.call(Lifespan.java:125) 	
at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:133) 	... 9 more 
Caused by: java.lang.NumberFormatException: For input string: "" 	
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) 	
at java.lang.Integer.parseInt(Integer.java:504) 	
at java.lang.Integer.parseInt(Integer.java:527) 	
at com.rultor.agents.daemons.EndsDaemon.end(EndsDaemon.java:115) 	
at com.rultor.agents.daemons.EndsDaemon.process(EndsDaemon.java:100):  	
at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78) 	
at com.rultor.spi.Agent$Iterative.execute(Agent.java:76) 	
at com.rultor.web.Lifespan.routine(Lifespan.java:215) 	
at com.rultor.web.Lifespan.safe_aroundBody4(Lifespan.java:192) 	
at com.rultor.web.Lifespan$AjcClosure5.run(Lifespan.java:1)
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.46.1`
