### ISSUE TITLE
sass-maven-plugin fails on Mac: can't convert String into Array

### ISSUE THREAD

**Issue by adko-pl** [yegor256/rultor#764]
`mvn clean install -Pqulice` fails with:

	[INFO] --- sass-maven-plugin:1.1.1:update-stylesheets (generate-css) @ rultor ---
	[INFO] Compiling SASS Templates
	[INFO] Queing SASS Template for compile: /private/tmp/rultor/src/main/scss => /private/tmp/rultor/target/css
	TypeError: can't convert String into Array
	       + at org/jruby/RubyArray.java:2963
	  (root) at <script>:5
	org.jruby.embed.EvalFailedException: (TypeError) can't convert String into Array
		at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:136)
		at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
		at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:153)
		at org.jasig.maven.plugin.sass.AbstractSassMojo.executeSassScript(AbstractSassMojo.java:191)
		at org.jasig.maven.plugin.sass.UpdateStylesheetsMojo.execute(UpdateStylesheetsMojo.java:43)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
		at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	Caused by: org.jruby.exceptions.RaiseException: (TypeError) can't convert String into Array
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time: 7.836 s
	[INFO] Finished at: 2015-01-31T09:59:54+01:00
	[INFO] Final Memory: 26M/367M
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal org.jasig.maven:sass-maven-plugin:1.1.1:update-stylesheets (generate-css) on project rultor: Failed to execute SASS ruby script:
	[ERROR] require 'rubygems'
	[ERROR] env = { 'GEM_PATH' => [
	[ERROR] '/private/tmp/rultor/target/rubygems'
	[ERROR] ] }
	[ERROR] env['GEM_PATH'] += ENV['GEM_PATH'] unless ENV['GEM_PATH'].nil?
	[ERROR] Gem.paths = env
	[ERROR] require 'sass/plugin'
	[ERROR] require 'java'
	[ERROR] Sass::Plugin.options.merge!(
	[ERROR] :cache_location => '/private/tmp/rultor/target/sass_cache',
	[ERROR] :style => :expanded,
	[ERROR] :cache => true,
	[ERROR] :unix_newlines => true,
	[ERROR] :css_location => '/private/tmp/rultor/target/css',
	[ERROR] :template_location => '/private/tmp/rultor/src/main/scss',
	[ERROR] :always_update => true
	[ERROR] )
	[ERROR] Sass::Plugin.on_compilation_error {|error, template, css| $compiler_callback.compilationError(error.message, template, css) }
	[ERROR] Sass::Plugin.on_updated_stylesheet {|template, css| $compiler_callback.updatedStylesheeet(template, css) }
	[ERROR] Sass::Plugin.on_template_modified {|template| $compiler_callback.templateModified(template) }
	[ERROR] Sass::Plugin.on_template_created {|template| $compiler_callback.templateCreated(template) }
	[ERROR] Sass::Plugin.on_template_deleted {|template| $compiler_callback.templateDeleted(template) }
	[ERROR] Sass::Plugin.update_stylesheets: org.jruby.exceptions.RaiseException: (TypeError) can't convert String into Array

my setup:
OS X 10.10
javac 1.8.0_25
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
ruby gems version 2.4.4

**Comment by yegor256** [comment]
@it's a known issue, in the plugin, see https://github.com/Jasig/sass-maven-plugin/issues/47 before running Maven do:

```
unset GEM_PATH
```

**Comment by bcostea** [comment]
thanks for the comment :)
