### ISSUE TITLE
JSON error in QnMerge:112

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#774]
```
Feb 14 05:14:55 www.rultor.com user:  [WARN] c0afd56 com.jcabi.log.VerboseRunnable: swallowed exception: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonObject 	at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:139) 	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPool...
Feb 14 05:14:55 www.rultor.com ...Executor$Worker.run(ThreadPoolExecutor.java:  615) 	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220) 	at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.IllegalStateException: java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonObject 	at com.rultor.web.Lifespan.uninterrupted(Lifespan.java:175) 	at com.rultor.web.Lifespan.access$000(Lifespan.java:86) 	at com.rultor.web.Lifespan$1.call(Lifespan.java:128) 	at com.rultor.web.Lifespan$1.call(Lifespan.java:125) 	at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:133) 	... 9 more Caused by: java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonObject 	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonObject(JsonObjectBuilderImpl.java:184) 	at com.rultor.agents.github.qtn.QnMerge.pack(QnMerge.java:  112) 	at com.rultor.agents.github.qtn.QnMerge.understand(QnMerge.java:84) 	at com.rultor.agents.github.qtn.QnAskedBy.understand(QnAskedBy.java:106) 	at com.rultor.agents.github.qtn.QnIfContains.understand(QnIfContains.java:78) 	at com.rultor.agents.github.Question$FirstOf.understand(Question.java:88) 	at com.rultor.agents.github.qtn.QnByArchitect.understand(QnByArchitect.java:97) 	at com.rultor.agents.github.qtn.QnAlone.understand(QnAlone.java:96) 	at com.rultor.agents.github.qtn.QnIfCollaborator.understand(QnIfCollaborator.java:84) 	at com.rultor.agents.github.qtn.QnFollow.understand(QnFollow.java:80) 	at com.rultor.agents.github.Question$FirstOf.understand(Question.java:88) 	at com.rultor.agents.github.qtn.QnParametrized.understand(QnParametrized.java:85) 	at com.rultor.agents.github.qtn.QnReferredTo.understand(QnReferredTo.java:88) 	at c...
Feb 14 05:14:55 www.rultor.com ...om.rultor.agents.github.qtn.QnNotSelf.understand(QnNotSelf.ja:  75) 	at com.rultor.agents.github.qtn.QnSince.understand(QnSince.java:79) 	at com.rultor.agents.github.Understands.parse(Understands.java:175) 	at com.rultor.agents.github.Understands.process(Understands.java:117) 	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78) 	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76) 	at com.rultor.web.Lifespan.routine(Lifespan.java:215) 	at com.rultor.web.Lifespan.safe_aroundBody4(Lifespan.java:192) 	at com.rultor.web.Lifespan$AjcClosure5.run(Lifespan.java:1) 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115) 	at com.rultor.web.Lifespan.safe(Lifespan.java:187) 	at com.rultor.web.Lifespan.uninterrupted(Lifespan.java:165) 	... 13 more  
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.49.3`
