### ISSUE TITLE
exception in AchivesDaemon

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#780]

**Comment by yegor256** [comment]
that's what is happening:

```
[WARN] BUILD com.rultor.agents.daemons.ArchivesDaemon: col: Invalid or incomplete multibyte or wide character 
[WARN] BUILD com.jcabi.log.VerboseRunnable: swallowed exception: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.IllegalArgumentException: non-zero exit code #1: dir='/tmp/rultor-uvYR'; if [ -r "${dir}/stdout" ]; then cat "${dir}/stdout" | col -b; else echo 'stdout not found, internal error'; fi 	at com.jcabi.log.VerboseRunnable$1.run(VerboseRunnable.java:139) 	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) 	at java.util.concurrent.ScheduledThreadP...
```

**Comment by yegor256** [comment]
Here is the issue:

```
col: Invalid or incomplete multibyte or wide character
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.49.5`
