### ISSUE TITLE
Rultor homepage broken

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#798]
>
R
BUILD
Internal Application Error
Something went terribly wrong. The system can't serve your request at the moment. We've been already notified about this situation and will start working on it really soon. In the meantime, please get back to the site and try to do the same operation again. Maybe it will work, you know :)
>
The text below is a detailed description of your HTTP request and a stacktrace of the runtime exception thrown by JVM. If you want to help us, please post this text as a new issue to Github.
>
java.lang.ArrayIndexOutOfBoundsException: 95
	at org.takes.facets.auth.CcHex.decode(CcHex.java:90)
	at org.takes.facets.auth.PsCookie.enter(PsCookie.java:79)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:67)
	at org.takes.facets.auth.TsAuth.route(TsAuth.java:82)
	at org.takes.facets.flash.TsFlash.route(TsFlash.java:88)
	at org.takes.ts.TsWithHeaders.route(TsWithHeaders.java:87)
	at org.takes.facets.fallback.TsFallback.route(TsFallback.java:96)
	at org.takes.ts.TsMeasured$1.route(TsMeasured.java:62)
	at org.takes.ts.TsWrap.route(TsWrap.java:57)
	at org.takes.ts.TsWithHeaders.route(TsWithHeaders.java:87)
	at com.rultor.web.App.route(App.java:169)
	at org.takes.http.BkBasic.print(BkBasic.java:106)
	at org.takes.http.BkBasic.accept(BkBasic.java:90)
	at org.takes.http.BkSafe.accept(BkSafe.java:56)
	at org.takes.http.BkParallel$1.run(BkParallel.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yegor256** [comment]
works fine now
