### ISSUE TITLE
XPath 1.0 in status.xsl, instead of 2.0

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#815]
```
[ERROR] BUILD com.jcabi.xml.XSLDocument$1: Could not find function: current-dateTime; Line#: 126; Column#: 104 
Mar 31 04:48:16 www.rultor.com user:  [ERROR] BUILD com.jcabi.xml.XSLDocument$1: function token not found.; Line#: 126; Column#: 104 
Mar 31 04:48:16 www.rultor.com user:  [ERROR] BUILD com.jcabi.xml.XSLDocument$1: java.lang.NullPointerException 
Mar 31 04:48:16 www.rultor.com user:  [ERROR] BUILD com.rultor.Routine: #run(): java.lang.NullPointerException 	at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:269) 	at com.jcabi.xml.XSLDocument.applyTo(XSLDocument.java:244) 	at com.rultor.agents.github.qtn.QnStatus.understand(QnStatus.java:138) 	at com.rultor.agents.github.qtn.QnIfContains.understand(QnIfContains.java:79) 	at com.rultor.agents.github.Question$FirstOf.understand(Question.java:88) 	at com.rultor.agents.github.qtn.QnParametrized.understand(QnParametrized.java:85) 	at com.rultor.agents.github.qtn.QnReferr...
Mar 31 04:48:16 www.rultor.com ...edTo.understand(QnReferredTo.java:  88) 	at com.rultor.agents.github.qtn.QnNotSelf.understand(
```

Looks like we have XPath 1.0 in runtime, for some reason

**Comment by alex-palevsky** [comment]
@yegor256 this is your task now, help us

**Comment by alex-palevsky** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-cd793cf5

**Comment by yegor256** [comment]
fixed

**Comment by alex-palevsky** [comment]
@yegor256 Much obliged! I have added **38 mins** to your account in payment "000-3865519a", 618 hours and 27 mins spent

age=2889, that's why a bonus here for fast delivery

+38 added to your rating, at the moment it is: [+9375](http://www.netbout.com/b/35008?open=rating)
