### ISSUE TITLE
refused requests to Twitter

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#816]
```
[WARN] 792a86f com.rultor.agents.twitter.OAuthTwitter: java.io.IOException: 403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following). message - Status is a duplicate. code - 187  Relevant discussions can be found on the Internet at: 	http://www.google.co.jp/search?q=2fc5b7cb or 	http://www.google.co.jp/search?q=0e1dbbf5 TwitterException{exceptionCode=[2fc5b7cb-0e1dbbf5], statusCode=403, message=Status is a duplicate., code=187, retryAfter=-1, rateLimitStatus=null, version=4.0.2} 	at com.rultor.agents.twitter.OAuthTwitter.post_aroundBody0(OAuthTwitter.java:99) 	at com.rultor.agents.twitter.OAuthTwitter$AjcClosure1.run(OAuthTwitter.java:1) 	at org.aspectj.run...
Mar 31 20:04:10 www.rultor.com ...time.reflect.JoinPointImpl.proceed(JoinPointImpl.java:  149) 	at com.jcabi.aspects.aj.QuietExceptionsLogger.wrap(QuietExceptionsLogger.java:82) 	at com.rultor.agents.twitter.OAuthTwitter.post(OAuthTwitter.java:92) 	at com.rultor.agents.twitter.Tweets.process(Tweets.java:91) 	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78) 	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76) 	at com.rultor.Routine.process(Routine.java:142) 	at com.rultor.Routine.safe_aroundBody0(Routine.java:160) 	at com.rultor.Routine$AjcClosure1.run(Routine.java:1) 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115) 	at com.rultor.Routine.safe(Routine.java:155) 	at com.rultor.Routine.run(Routine.java:112) 	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198) 	at com.j...
Mar 31 20:04:10 www.rultor.com ...cabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler:  179) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220) 	at java.lang.Thread.run(Thread.java:745) Caused by: 403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests ...
Mar 31 20:04:10 www.rultor.com ...are:  being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following). message - Status is a duplicate. code - 187  Relevant discussions can be found on the Internet at: 
```

**Comment by alex-palevsky** [comment]
@yegor256 it is your task now

**Comment by alex-palevsky** [comment]
@yegor256 many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `000-4bc3910d`

**Comment by alex-palevsky** [comment]
@yegor256 since there is no milestone yet I set it to "0.3"

**Comment by yegor256** [comment]
@alex-palevsky assign someone else pls

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 -30 points to your rating

**Comment by alex-palevsky** [comment]
> @alex-palevsky assign someone else pls

@yegor256 OK, I will try to assign someone else

**Comment by alex-palevsky** [comment]
@kujtimiihoxha can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by kujtimiihoxha** [comment]
@yegor256 how can I reproduce this issue?

**Comment by yegor256** [comment]
@kujtimiihoxha I don't think it's fixable (or reproducible). I'm closing, thanks.
