### ISSUE TITLE
crash on too big XML docs

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#817]
Rultor down: system outage

**Comment by yegor256** [comment]
this is the cause now:

```
#run(): java.lang.IllegalArgumentException: XML is too big 	at com.rultor.dynamo.DyTalk.modify(DyTalk.java:122) 	at com.rultor.cached.CdTalk.modify(CdTalk.java:93) 	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78) 	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76) 	at com.rultor.Routine.process(Routine.java:142) 	at com.rultor.Routine.safe_aroundBody0(Routine.java:160) 	at com.rultor.Routine$AjcClosure1.run(Routine.java:1) 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115) 	at com.rultor.Routine.safe(Routine.java:155) 	at com.rultor.Routine.run(Routine.java:112) 	at com.jcabi.log.VerboseRunnable....
Apr 01 04:08:39 www.rultor.com ...run(VerboseRunnable.java:  198) 	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220) 	at java.lang.Thread.run(Thread.java:745)  
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.2`

**Comment by yegor256** [comment]
@pinaf fixed, thanks for reporting
