### ISSUE TITLE
XML problem in QnStatus

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#820]
```
java.lang.NoSuchMethodException: For extension function, could not find method
org.apache.xml.utils.NodeVector.ago([ExpressionContext,] ). 	
at org.apache.xalan.extensions.MethodResolver.getMethod(MethodResolver.java:274) 	
at org.apache.xalan.extensions.ExtensionHandlerJavaPackage.callFunction(ExtensionHandlerJavaPackage.java:370) 
```

**Comment by yegor256** [comment]
I can't understand what Xalan is doing there :(

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.3`

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.3`

**Comment by yegor256** [comment]
@rultor status

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.3`

**Comment by yegor256** [comment]
@rultor status
