### ISSUE TITLE
NULL in CommitsLog

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#839]
```
java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonObject 
at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonObject(JsonObjectBuilderImpl.java:184) 
at com.rultor.agents.github.CommitsLog.build(CommitsLog.java:100) 
at com.rultor.agents.github.CommentsTag.process(CommentsTag.java:118) 
at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78) 
```

**Comment by alex-palevsky** [comment]
@yegor256 added "bug" tag to this issue

**Comment by alex-palevsky** [comment]
@yegor256 attached this issue to milestone "2.0" (let me know if this is wrong)

**Comment by alex-palevsky** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-645caad1`

**Comment by yegor256** [comment]
similar problem:

```
java.lang.ClassCastException: Cannot cast javax.json.JsonValue$1 to javax.json.JsonString
        at java.lang.Class.cast(Class.java:3176)
        at com.jcabi.github.SmartJson.value_aroundBody6(SmartJson.java:143)
        at com.jcabi.github.SmartJson$AjcClosure7.run(SmartJson.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
        at com.jcabi.github.SmartJson.value(SmartJson.java:120)
        at com.jcabi.github.SmartJson.text_aroundBody0(SmartJson.java:81)
        at com.jcabi.github.SmartJson$AjcClosure1.run(SmartJson.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
        at com.jcabi.github.SmartJson.text(SmartJson.java:81)
        at com.jcabi.github.Release$Smart.publishedAt_aroundBody42(Release.java:336)
        at com.jcabi.github.Release$Smart$AjcClosure43.run(Release.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
        at com.jcabi.github.Release$Smart.publishedAt(Release.java:336)
        at com.rultor.agents.github.CommentsTag.previous(CommentsTag.java:146)
        at com.rultor.agents.github.CommentsTag.process(CommentsTag.java:114)
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.13`

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.13`
