### ISSUE TITLE
Internal Application Error when I check the progress of a merge

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#840]
Error occurs when I try to open this [link](http://www.rultor.com/t/3479-94368390)
In the error message I see

> If you want to help us, please post this text as a new issue to Github.

So I created this issue

```
R
7099abc
Internal Application Error
Something went terribly wrong. The system can't serve your request at the moment. We've been already notified about this situation and will start working on it really soon. In the meantime, please get back to the site and try to do the same operation again. Maybe it will work, you know :)

The text below is a detailed description of your HTTP request and a stacktrace of the runtime exception thrown by JVM. If you want to help us, please post this text as a new issue to Github.

java.io.IOException: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcabi.ssh.SSH.session(SSH.java:336)
	at com.jcabi.ssh.SSH.exec(SSH.java:218)
	at com.rultor.agents.daemons.Tail$SSHConnect.read(Tail.java:230)
	at com.rultor.agents.daemons.Tail.read(Tail.java:135)
	at com.rultor.web.TkDaemon.html(TkDaemon.java:139)
	at com.rultor.web.TkDaemon.act(TkDaemon.java:119)
	at org.takes.facets.forward.TkForward.act(TkForward.java:61)
	at org.takes.facets.fallback.TkFallback.act(TkFallback.java:78)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:57)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:64)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkWithHeader$1.act(TkWithHeader.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:68)
	at org.takes.tk.TkWrap.act(TkWrap.java:58)
	at org.takes.http.BkBasic.print(BkBasic.java:89)
	at org.takes.http.BkBasic.accept(BkBasic.java:73)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkParallel$1.run(BkParallel.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:332)
	... 22 more
```

**Comment by yegor256** [comment]
@dmzaytsev it's a temporary issue on the server, non-reproducable, but thanks for reporting anyway
