### ISSUE TITLE
Rultor down: com.jcraft.jsch.JSchException: timeout: socket is not established

### ISSUE THREAD

**Issue by pinaf** [yegor256/rultor#844]
>
the system is down, for 33min

```
java.io.IOException: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcabi.ssh.SSH.session(SSH.java:336)
	at com.jcabi.ssh.SSH.exec(SSH.java:218)
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:103)
	at com.rultor.agents.daemons.StartsDaemon.process(StartsDaemon.java:94)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.jcabi.ssh.SSH.session(SSH.java:332)
	... 22 more
```

**Comment by yegor256** [comment]
@pinaf that's because contabo is down (we host our servers there): http://contabo-status.com/

**Comment by pinaf** [comment]
@yegor256 thanks
