### ISSUE TITLE
Script crashes when no directory present

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#852]
```
java.lang.IllegalArgumentException: non-zero exit code #1: cd '/tmp/rultor-PH8a' && /bin/bash 'stop.sh' >> stdout
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:105)
	at com.jcabi.ssh.Shell$Empty.exec(Shell.java:138)
	at com.rultor.agents.daemons.Script.exec(Script.java:74)
	at com.rultor.agents.daemons.StopsDaemon.process(StopsDaemon.java:66)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.10`
