### ISSUE TITLE
Answer.post: broken Unicode text at line

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#855]
```
java.lang.IllegalStateException: broken Unicode text at line #0 in '[{"url":"https://api.github.com/repos/teamed/xocke..19381..play/MAVEN/MojoFailureException\n\n```"}]' (19493 bytes)
	at com.jcabi.http.request.DefaultResponse.body(DefaultResponse.java:147)
	at com.jcabi.http.response.AbstractResponse.body(AbstractResponse.java:90)
	at com.jcabi.http.response.JsonResponse.body(JsonResponse.java:66)
	at com.jcabi.http.response.JsonResponse.json(JsonResponse.java:108)
	at com.jcabi.github.RtValuePagination$Items.fetch(RtValuePagination.java:211)
	at com.jcabi.github.RtValuePagination$Items.hasNext(RtValuePagination.java:185)
	at com.jcabi.github.Smarts$1.hasNext(Smarts.java:90)
	at com.google.common.collect.Iterators.addAll(Iterators.java:361)
	at com.google.common.collect.Lists.newArrayList(Lists.java:160)
	at com.google.common.collect.Lists.newArrayList(Lists.java:144)
	at com.rultor.agents.github.Answer.post(Answer.java:85)
	at com.rultor.agents.github.Reports.process(Reports.java:109)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
```

**Comment by yegor256** [comment]
@rultor release tag is `1.52.12`

**Comment by alex-palevsky** [comment]
@yegor256 tag "bug" added

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.12`
