### ISSUE TITLE
NULL in CommitsLog (continued)

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#857]
```
[ERROR] 5207de9 com.rultor.Routine: #run(): java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonObject 	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonObject(JsonObjectBuilderImpl.java:184) 	at com.rultor.agents.github.CommitsLog.build(CommitsLog.java:105) 	at com.rultor.agents.github.CommentsTag.process(CommentsTag.java:120) 	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78) 	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76) 	at com.rultor.Routine.process(Routine.java:165) 	at com.rultor.Routine.safe_aroundBo
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.52.14`
