### ISSUE TITLE
crashes with issue/PR is absent

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#889]
```
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20) 	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:117) 	at com.jcabi.github.RtJson.fetch_aroundBody0(RtJson.java:77) 	at com.jcabi.github.RtJson$AjcClosure1.run(RtJson.java:1) 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212) 	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1) 	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136) 	at com.jcabi.github.RtJson.fetch(RtJson.java:77) 	at com.jcabi.github.RtPull.jso...
Jul 07 01:01:04 www.rultor.com ...n_aroundBody14(RtPull.java:  195) 	at com.jcabi.github.RtPull$AjcClosure15.run(RtPull.java:1) 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212) 	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1) 	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136) 	at com.jcabi.github.RtPull.json(RtPull.java:195) 	at com.rultor.agents.github.qtn.QnIfUnlocked.understand(QnIfUnlocked.java:97) 	at com.rultor.agents.github.qtn.QnAskedBy.understand(QnAskedBy.java:106) 	at com.rultor.agents.github.qtn.QnIfContains.understand(QnIfContains.java:79) 	...
Jul 07 01:01:04 www.rultor.com ...at:  com.rultor.agents.github.Question$FirstOf.understand(Question.java:88) 	at com.rultor.agents.github.qtn.QnByArchitect.understand(QnByArchitect.java:117) 	at com.rultor.agents.github.qtn.QnAlone.understand(QnAlone.java:96) 	at com.rultor.agents.github.qtn.QnIfCollaborator.understand(QnIfCollaborator.java:84) 	at com.rultor.agents.github.qtn.QnFollow.understand(QnFollow.java:80) 	at com.rultor.agents.github.Question$FirstOf.understand(Question.java:88) 	at com.rultor.agents.github.qtn.QnParametrized.understand(QnParametrized.java:85) 	at com.rultor.agents.github.qtn.QnReferredTo.understand(QnReferredTo.java:88) 	at com.rultor.agents.github.qtn.QnNotSelf.understand(QnNotSelf.java:75) 	at com.rultor.agents.github.qtn.QnSince.understand(...
Jul 07 01:01:04 www.rultor.com ...QnSince.java:  79) 	at com.rultor.agents.github.Understands.parse(Understands.java:176) 	at com.rultor.agents.github.Understands.process(Understands.java:117) 	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78) 	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76) 	at com.rultor.Routine.process(Routine.java:165) 	at com.rultor.Routine.safe_aroundBody0(Routine.java:145) 	at com.rultor.Routine$AjcClosure1.run(Routine.java:1) 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115) 	at com.rultor.Routine.safe(Routine.java:140) 	at com.rultor.Routine.run(Routine.java:113) 	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.ja...
```

**Comment by yegor256** [comment]
@rultor release, tag is `1.56.1`
