### ISSUE TITLE
Rultor is down: non-zero exit code #1: mktemp -d -t rultor-XXXX

### ISSUE THREAD

**Issue by longtimeago** [yegor256/rultor#927]
```
Unfortunately, the system is down, for 19min already

Please, email this page to bug@rultor.com

java.lang.IllegalArgumentException: non-zero exit code #1: mktemp -d -t rultor-XXXX
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:105)
	at com.rultor.agents.daemons.StartsDaemon.run_aroundBody0(StartsDaemon.java:119)
	at com.rultor.agents.daemons.StartsDaemon$AjcClosure1.run(StartsDaemon.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:81)
	at com.rultor.agents.daemons.StartsDaemon.run(StartsDaemon.java:116)
	at com.rultor.agents.daemons.StartsDaemon.process(StartsDaemon.java:97)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.spi.Agent$Iterative.execute(Agent.java:76)
	at com.rultor.Routine.process(Routine.java:165)
	at com.rultor.Routine.safe_aroundBody0(Routine.java:145)
	at com.rultor.Routine$AjcClosure1.run(Routine.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
	at com.rultor.Routine.safe(Routine.java:140)
	at com.rultor.Routine.run(Routine.java:113)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at com.jcabi.aspects.aj.MethodScheduler$Service$1.run(MethodScheduler.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```
I think rultor is out of disk space

**Comment by yegor256** [comment]
@longtimeago yeah, we're out of disk space. I'm working on it

**Comment by yegor256** [comment]
@longtimeago it's fixed
