### ISSUE TITLE
 test com.rultor.agents.daemons.StartsDaemonITCase fails

### ISSUE THREAD

**Issue by rfqu** [yegor256/rultor#966]
(test can be excuded with @Ignore annotation, restore it first)

diagnostics:

```
com.rultor.agents.daemons.StartsDaemon: #run(): attempt #1 of 3 failed in 3s (3s waiting already) with java.lang.IllegalArgumentException: non-zero exit code #1: cd '/home/jim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
/tmp/rultor-FR84' && chmod a+x run.sh && echo 'run.sh failed to start' > stdout && ( ( nohup ./run.sh </dev/null >stdout 2>&1; echo $? >status ) </dev/null >/dev/null & )
	at com.jcabi.ssh.Shell$Safe.exec(Shell.java:105)
	at com.jcabi.ssh.Shell$Empty.exec(Shell.java:138)
	at com.rultor.agents.daemons.StartsDaemon.run_aroundBody0(StartsDaemon.java:155)
	at com.rultor.agents.daemons.StartsDaemon$AjcClosure1.run(StartsDaemon.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.Repeater.wrap(Repeater.java:82)
	at com.rultor.agents.daemons.StartsDaemon.run(StartsDaemon.java:116)
	at com.rultor.agents.daemons.StartsDaemon.process(StartsDaemon.java:97)
	at com.rultor.agents.AbstractAgent.execute(AbstractAgent.java:78)
	at com.rultor.agents.daemons.StartsDaemonITCase.startsDaemon(StartsDaemonITCase.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:113)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:85)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:82)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:951)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:831)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:729)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_rsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_dsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ecdsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ed25519_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Accepted publickey for jim from 127.0.0.1 port 43778 ssh2: RSA 5b:8c:24:46:c2:5e:a4:f2:5c:6e:ce:85:06:c9:cf:44
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_rsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_dsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ecdsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ed25519_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Accepted publickey for jim from 127.0.0.1 port 43779 ssh2: RSA 5b:8c:24:46:c2:5e:a4:f2:5c:6e:ce:85:06:c9:cf:44
[[0;33mWARN[m] java.lang.Boolean: bash: /home/jim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
[[0;33mWARN[m] java.lang.Boolean: /tmp/rultor-NN1A/file.bin: No such file or directory
[[0;37mINFO[m] com.rultor.agents.daemons.StartsDaemon: "file.bin" uploaded into /home/jim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
/tmp/rultor-NN1A
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_rsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_dsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ecdsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ed25519_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Accepted publickey for jim from 127.0.0.1 port 43781 ssh2: RSA 5b:8c:24:46:c2:5e:a4:f2:5c:6e:ce:85:06:c9:cf:44
[[0;37mINFO[m] com.rultor.agents.daemons.StartsDaemon: /home/jim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
[[0;33mWARN[m] com.rultor.agents.daemons.StartsDaemon: bash: line 1: cd: /home/jim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
[[0;33mWARN[m] com.rultor.agents.daemons.StartsDaemon: /tmp/rultor-NN1A: No such file or directory
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_rsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_dsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ecdsa_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Could not load host key: /etc/ssh/ssh_host_ed25519_key
[[0;33mWARN[m] com.jcabi.log.VerboseProcess: >> Accepted publickey for jim from 127.0.0.1 port 43783 ssh2: RSA 5b:8c:24:46:c2:5e:a4:f2:5c:6e:ce:85:06:c9:cf:44
[[0;33mWARN[m] com.jcabi.ssh.Shell$Empty: bash: line 1: cd: /home/jim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
[[0;33mWARN[m] com.jcabi.ssh.Shell$Empty: /tmp/rultor-NN1A: No such file or directory
```

**Comment by alex-palevsky** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@rfqu what should I do to reproduce it? When I run `mvn clean install` I don't see anything like this...

**Comment by rfqu** [comment]
it fails on Windows 8.1 and passes on Ubuntu 15.10.
If Windows is not important, this issue can be closed as not reproducible.

**Comment by yegor256** [comment]
@rfqu if you run `mvn clean install`, the build will fail on Windows. it's not supposed to work on this platform
